
export const SET_CIRCUIT_ID_ID = "SET_CIRCUIT_ID_ID";
export const SET_CIRCUIT_NAME_ID = "SET_CIRCUIT_NAME_ID";

export const SET_CIRCUIT_SAVED_ID = "SET_CIRCUIT_SAVED_ID";

export const SET_CIRCUIT_SAVING_START_ID = "SET_CIRCUIT_SAVING_START_ID";
export const SET_CIRCUIT_SAVING_FINISH_ID = "SET_CIRCUIT_SAVING_FINISH_ID";

export const TOGGLE_CIRCUIT_LOCKED_ID = "TOGGLE_CIRCUIT_LOCKED_ID";
