
export const LOGIN_ACTION_ID = "LOGIN_ACTION_ID";
export const LOGOUT_ACTION_ID = "LOGOUT_ACTION_ID";

export const LOAD_CIRCUITS_START_ID = "LOAD_CIRCUITS_START_ID";
export const LOAD_CIRCUITS_FINISH_ID = "LOAD_CIRCUITS_FINISH_ID";
export const SET_AUTOSAVE_ACTION_ID = "SET_AUTOSAVE_ACTION_ID";