import { defineConfig } from "oxlint";

export default defineConfig({
    "plugins": ["typescript", "jsdoc", "react", "jest", "unicorn", "jsx-a11y", "import"],
    "jsPlugins": [{ "name": "react-hooks-js", "specifier": "eslint-plugin-react-hooks" }],
    "categories": {
        "correctness": "off",
    },
    "env": {
        "builtin": true,
        "browser": true,
        "es2026": true,
        "jest": true,
        "node": true,
    },
    "settings": {
        "react": {
            "version": "999.999.999",
        },
    },
    "ignorePatterns": [
        "**/*.js",
        "**/*.cjs",
        "**/*.mjs",
        "**/*.d.ts",
        "**/proto/*.ts",
        // TODO: Don't ignore analog once work on it resumes
        "src/projects/analog/**",
        "scripts/bundler/**",
    ],
    "rules": {
        "curly": "error",
        "constructor-super": "error",
        "for-direction": "error",
        "no-async-promise-executor": "error",
        "no-class-assign": "error",
        "no-compare-neg-zero": "error",
        "no-cond-assign": "error",
        "no-const-assign": "error",
        "no-constant-binary-expression": "error",
        "no-constant-condition": "error",
        "no-control-regex": "error",
        "no-debugger": "error",
        "no-delete-var": "error",
        "no-dupe-class-members": "error",
        "no-dupe-else-if": "error",
        "no-dupe-keys": "error",
        "no-duplicate-case": "error",
        "no-empty": "error",
        "no-empty-character-class": "error",
        "no-empty-pattern": "off",
        "no-empty-static-block": "error",
        "no-ex-assign": "error",
        "no-extra-boolean-cast": "error",
        "no-fallthrough": "error",
        "no-func-assign": "error",
        "no-global-assign": "error",
        "no-import-assign": "error",
        "no-invalid-regexp": "error",
        "no-irregular-whitespace": "error",
        "no-loss-of-precision": "error",
        "no-misleading-character-class": "error",
        "no-new-array": "off",
        "no-new-native-nonconstructor": "error",
        "no-nonoctal-decimal-escape": "error",
        "no-obj-calls": "error",
        "no-prototype-builtins": "error",
        "no-redeclare": "error",
        "no-regex-spaces": "error",
        "no-self-assign": "error",
        "no-setter-return": "error",
        "no-shadow-restricted-names": "error",
        "no-sparse-arrays": "error",
        "no-this-before-super": "error",
        "no-unexpected-multiline": "error",
        "no-unsafe-finally": "error",
        "no-unsafe-negation": "error",
        "no-unsafe-optional-chaining": "error",
        "no-unused-labels": "error",
        "no-unused-private-class-members": "error",
        "no-unused-vars": [
            "error",
            {
                // Oxlint can't seem to recognize that (o): o is Obj => (true) is indeed using `o` so adding to the ignore pattern
                "argsIgnorePattern": "_|o",
                "varsIgnorePattern": "_",
                "caughtErrorsIgnorePattern": "_",
                "args": "after-used",
                "ignoreRestSiblings": false,
            },
        ],
        "no-useless-backreference": "error",
        "no-useless-catch": "error",
        "no-useless-escape": "error",
        "no-with": "error",
        "require-yield": "error",
        "use-isnan": "error",
        "valid-typeof": "error",
        "no-self-compare": "error",
        "default-case-last": "error",
        "eqeqeq": "error",
        "no-else-return": "error",
        "no-useless-return": "error",
        "no-var": "error",
        "no-console": [
            "error",
            {
                "allow": ["warn", "error"],
            },
        ],
        "prefer-const": "error",
        "no-array-constructor": "error",
        "arrow-body-style": "error",
        "no-unused-expressions": "off",
        "jsdoc/check-access": "error",
        "jsdoc/check-property-names": "error",
        "jsdoc/check-tag-names": [
            "error",
            {
                "jsxTags": true,
            },
        ],
        "jsdoc/empty-tags": "error",
        "jsdoc/require-param-description": "error",
        "jsdoc/require-param-name": "error",
        "jsdoc/require-param": "error",
        "jsdoc/require-property": "error",
        "jsdoc/require-property-description": "error",
        "jsdoc/require-property-name": "error",
        "jsdoc/require-returns-description": "error",
        "jsdoc/require-returns": "error",
        "jsdoc/require-yields": "error",
        "react/display-name": "error",
        "react/jsx-key": "error",
        "react/jsx-no-comment-textnodes": "error",
        "react/jsx-no-duplicate-props": "error",
        "react/jsx-no-target-blank": "error",
        "react/jsx-no-undef": "error",
        "react/no-children-prop": "error",
        "react/no-danger-with-children": "error",
        "react/no-direct-mutation-state": "error",
        "react/no-find-dom-node": "error",
        "react/no-is-mounted": "error",
        "react/no-render-return-value": "error",
        "react/no-string-refs": "error",
        "react/no-unescaped-entities": "error",
        "react/button-has-type": "error",
        "react/forbid-elements": [
            "error",
            {
                "forbid": [
                    {
                        "element": "input",
                        "message": "use <InputField> instead",
                    },
                ],
            },
        ],
        "react/hook-use-state": "off",
        "react/no-danger": "error",
        "react/no-did-mount-set-state": "error",
        "react/no-multi-comp": "off",
        "react/no-namespace": "error",
        "react/no-redundant-should-component-update": "error",
        "react/no-this-in-sfc": "error",
        "react/no-unsafe": "error",
        "react/no-will-update-set-state": "error",
        "react/self-closing-comp": [
            "error",
            {
                "component": true,
                "html": false,
            },
        ],
        "react/style-prop-object": "error",
        "react/void-dom-elements-no-children": "error",
        "react/jsx-boolean-value": ["error", "never"],
        "react/jsx-curly-brace-presence": [
            "error",
            {
                "props": "never",
                "children": "never",
                "propElementValues": "always",
            },
        ],
        "react/jsx-filename-extension": [
            "error",
            {
                "extensions": [".tsx"],
            },
        ],
        "react/jsx-fragments": ["error", "syntax"],
        "react/jsx-handler-names": "error",
        "react/jsx-no-constructed-context-values": "error",
        "react/jsx-no-script-url": "error",
        "react/jsx-no-useless-fragment": "error",
        "react/jsx-pascal-case": "error",
        "react/no-unknown-property": [
            "error",
            {
                "ignore": ["unselectable"],
            },
        ],
        "jest/expect-expect": "warn",
        "jest/no-alias-methods": "warn",
        "jest/no-commented-out-tests": "warn",
        "jest/no-conditional-expect": "error",
        "jest/no-deprecated-functions": "error",
        "jest/no-disabled-tests": "warn",
        "jest/no-done-callback": "error",
        "jest/no-export": "error",
        "jest/no-focused-tests": "error",
        "jest/no-identical-title": "error",
        "jest/no-interpolation-in-snapshots": "error",
        "jest/no-jasmine-globals": "error",
        "jest/no-mocks-import": "error",
        "jest/no-standalone-expect": "error",
        "jest/no-test-prefixes": "error",
        "jest/valid-describe-callback": "error",
        "jest/valid-expect": "error",
        "jest/valid-title": "error",
        "jest/prefer-to-be": "error",
        "jest/prefer-to-contain": "error",
        "jest/prefer-to-have-length": "error",
        "unicorn/catch-error-name": [
            "error",
            {
                "name": "e",
            },
        ],
        "unicorn/consistent-assert": "error",
        "unicorn/consistent-date-clone": "error",
        "unicorn/consistent-empty-array-spread": "error",
        "unicorn/consistent-existence-index-check": "error",
        "unicorn/custom-error-definition": "error",
        "unicorn/empty-brace-spaces": "error",
        "unicorn/error-message": "error",
        "unicorn/escape-case": "error",
        "unicorn/explicit-length-check": "error",
        "unicorn/filename-case": [
            "error",
            {
                "cases": {
                    "camelCase": true,
                    "pascalCase": true,
                },
                "ignore": "^.*(IC|ID|IO|BCD|LED|JK|SR|AND|BUF|OR|XOR|SR|WASM|ASCII|OS|NG|SVG).*$",
            },
        ],
        "unicorn/new-for-builtins": "error",
        "unicorn/no-abusive-eslint-disable": "error",
        "unicorn/no-accessor-recursion": "error",
        "unicorn/no-anonymous-default-export": "error",
        "unicorn/no-array-method-this-argument": "error",
        "unicorn/no-await-expression-member": "error",
        "unicorn/no-await-in-promise-methods": "error",
        "unicorn/no-console-spaces": "error",
        "unicorn/no-document-cookie": "error",
        "unicorn/no-empty-file": "error",
        "unicorn/no-hex-escape": "error",
        "unicorn/no-instanceof-builtins": "error",
        "unicorn/no-invalid-fetch-options": "error",
        "unicorn/no-invalid-remove-event-listener": "error",
        "unicorn/no-lonely-if": "error",
        "unicorn/no-magic-array-flat-depth": "off",
        "unicorn/no-negated-condition": "off",
        "unicorn/no-negation-in-equality-check": "error",
        "unicorn/no-new-buffer": "error",
        "unicorn/no-null": "error",
        "unicorn/no-process-exit": "error",
        "unicorn/no-single-promise-in-promise-methods": "error",
        "unicorn/no-static-only-class": "error",
        "unicorn/no-thenable": "error",
        "unicorn/no-this-assignment": "error",
        "unicorn/no-typeof-undefined": "error",
        "unicorn/no-unnecessary-array-flat-depth": "error",
        "unicorn/no-unnecessary-array-splice-count": "error",
        "unicorn/no-unnecessary-await": "error",
        "unicorn/no-unnecessary-slice-end": "error",
        "unicorn/no-unreadable-array-destructuring": "error",
        "unicorn/no-unreadable-iife": "error",
        "unicorn/no-useless-fallback-in-spread": "error",
        "unicorn/no-useless-length-check": "error",
        "unicorn/no-useless-promise-resolve-reject": "error",
        "unicorn/no-useless-spread": "error",
        "unicorn/no-useless-switch-case": "error",
        "unicorn/no-useless-undefined": [
            "error",
            {
                "checkArguments": false,
            },
        ],
        "unicorn/no-zero-fractions": "error",
        "unicorn/number-literal-case": "error",
        "unicorn/numeric-separators-style": "error",
        "unicorn/prefer-add-event-listener": "error",
        "unicorn/prefer-array-find": "error",
        "unicorn/prefer-array-flat-map": "error",
        "unicorn/prefer-array-flat": "error",
        "unicorn/prefer-array-index-of": "error",
        "unicorn/prefer-array-some": "error",
        "unicorn/prefer-at": "error",
        "unicorn/prefer-blob-reading-methods": "error",
        "unicorn/prefer-code-point": "error",
        "unicorn/prefer-date-now": "error",
        "unicorn/prefer-default-parameters": "error",
        "unicorn/prefer-dom-node-append": "error",
        "unicorn/prefer-dom-node-dataset": "error",
        "unicorn/prefer-dom-node-remove": "error",
        "unicorn/prefer-dom-node-text-content": "error",
        "unicorn/prefer-event-target": "error",
        "unicorn/prefer-includes": "error",
        "unicorn/prefer-keyboard-event-key": "error",
        "unicorn/prefer-logical-operator-over-ternary": "error",
        "unicorn/prefer-math-min-max": "error",
        "unicorn/prefer-modern-dom-apis": "error",
        "unicorn/prefer-modern-math-apis": "error",
        "unicorn/prefer-module": "error",
        "unicorn/prefer-native-coercion-functions": "error",
        "unicorn/prefer-negative-index": "error",
        "unicorn/prefer-node-protocol": "error",
        "unicorn/prefer-object-from-entries": "error",
        "unicorn/prefer-optional-catch-binding": "error",
        "unicorn/prefer-prototype-methods": "error",
        "unicorn/prefer-reflect-apply": "error",
        "unicorn/prefer-regexp-test": "error",
        "unicorn/prefer-set-has": "error",
        "unicorn/prefer-set-size": "error",
        "unicorn/prefer-spread": "error",
        "unicorn/prefer-string-raw": "error",
        "unicorn/prefer-string-replace-all": "error",
        "unicorn/prefer-string-slice": "error",
        "unicorn/prefer-string-starts-ends-with": "error",
        "unicorn/prefer-string-trim-start-end": "error",
        "unicorn/prefer-structured-clone": "error",
        "unicorn/prefer-ternary": ["error", "only-single-line"],
        "unicorn/prefer-type-error": "error",
        "unicorn/relative-url-style": "error",
        "unicorn/require-array-join-separator": "error",
        "unicorn/require-number-to-fixed-digits-argument": "error",
        "unicorn/text-encoding-identifier-case": "error",
        "unicorn/throw-new-error": "error",
        "jsx-a11y/autocomplete-valid": [
            "warn",
            {
                "inputComponents": ["InputField"],
            },
        ],
        "jsx-a11y/lang": "warn",
        "jsx-a11y/alt-text": "warn",
        "jsx-a11y/anchor-has-content": "warn",
        "jsx-a11y/anchor-is-valid": "warn",
        "jsx-a11y/aria-activedescendant-has-tabindex": "warn",
        "jsx-a11y/aria-props": "warn",
        "jsx-a11y/aria-proptypes": "warn",
        "jsx-a11y/aria-role": "warn",
        "jsx-a11y/aria-unsupported-elements": "warn",
        "jsx-a11y/heading-has-content": "warn",
        "jsx-a11y/html-has-lang": "warn",
        "jsx-a11y/iframe-has-title": "warn",
        "jsx-a11y/img-redundant-alt": "warn",
        "jsx-a11y/media-has-caption": "warn",
        "jsx-a11y/mouse-events-have-key-events": "warn",
        "jsx-a11y/no-access-key": "warn",
        "jsx-a11y/no-autofocus": "warn",
        "jsx-a11y/no-distracting-elements": "warn",
        "jsx-a11y/no-noninteractive-tabindex": "warn",
        "jsx-a11y/no-redundant-roles": "warn",
        "jsx-a11y/no-static-element-interactions": "warn",
        "jsx-a11y/role-has-required-aria-props": "warn",
        "jsx-a11y/role-supports-aria-props": "warn",
        "jsx-a11y/scope": "warn",
        "jsx-a11y/tabindex-no-positive": "warn",
        "import/namespace": "error",
        "import/default": "error",
        "import/no-named-as-default": "warn",
        "import/no-named-as-default-member": "off",
        "import/no-duplicates": "error",
        "import/no-self-import": "error",
        "import/no-mutable-exports": "error",
        "import/first": "error",
        "import/extensions": [
            "error",
            "ignorePackages",
            {
                "ts": "never",
                "tsx": "never",
            },
        ],
        "import/no-cycle": "off",
        "react/rules-of-hooks": "error",
        "react/exhaustive-deps": "error",
        "typescript/ban-ts-comment": "error",
        "typescript/no-duplicate-enum-values": "error",
        "typescript/no-empty-object-type": "off",
        "typescript/no-extra-non-null-assertion": "error",
        "typescript/no-misused-new": "error",
        "typescript/no-namespace": "error",
        "typescript/no-non-null-asserted-optional-chain": "error",
        "typescript/no-require-imports": "error",
        "typescript/no-this-alias": "error",
        "typescript/no-unnecessary-type-constraint": "error",
        "typescript/no-unsafe-declaration-merging": "error",
        "typescript/no-unsafe-function-type": "error",
        "typescript/no-wrapper-object-types": "error",
        "typescript/prefer-as-const": "error",
        "typescript/prefer-namespace-keyword": "error",
        "typescript/triple-slash-reference": "error",
        "typescript/array-type": [
            "error",
            {
                "default": "array-simple",
            },
        ],
        "typescript/no-inferrable-types": "error",
        "typescript/consistent-type-assertions": "error",
        "typescript/no-var-requires": "error",

        // React Compiler rules, not expected to be supported natively in oxline in the near future
        "react-hooks-js/config": "error",
        "react-hooks-js/error-boundaries": "error",
        "react-hooks-js/gating": "error",
        "react-hooks-js/globals": "error",
        "react-hooks-js/immutability": "error",
        "react-hooks-js/preserve-manual-memoization": "error",
        "react-hooks-js/purity": "error",
        "react-hooks-js/refs": "error",
        "react-hooks-js/set-state-in-effect": "error",
        "react-hooks-js/set-state-in-render": "error",
        "react-hooks-js/static-components": "error",
        "react-hooks-js/unsupported-syntax": "warn",
        "react-hooks-js/use-memo": "error",
        "react-hooks-js/incompatible-library": "warn",
    },
    "overrides": [
        {
            "files": ["docs/**"],
            "rules": {
                "react/jsx-filename-extension": [
                    "error",
                    {
                        "extensions": [".jsx", ".tsx"],
                    },
                ],
            },
        },
        {
            "files": ["scripts/**"],
            "rules": {
                "no-console": "off",
                "import/extensions": "off",
                "unicorn/no-process-exit": "off",
            },
        },
        {
            "files": ["**/*.ts", "**/*.tsx", "**/*.mts", "**/*.cts"],
            "rules": {
                "constructor-super": "off",
                "no-class-assign": "off",
                "no-const-assign": "off",
                "no-dupe-class-members": "off",
                "no-dupe-keys": "off",
                "no-func-assign": "off",
                "no-import-assign": "off",
                "no-new-native-nonconstructor": "off",
                "no-obj-calls": "off",
                "no-redeclare": "off",
                "no-setter-return": "off",
                "no-this-before-super": "off",
                "no-unsafe-negation": "off",
                "no-with": "off",
                "prefer-rest-params": "error",
                "prefer-spread": "error",
            },
        },
        {
            "files": ["src/**/*.test.ts"],
            "rules": {
                "jest/no-commented-out-tests": "off",
                "jest/prefer-comparison-matcher": "error",
                "jest/prefer-equality-matcher": "error",
                "jest/expect-expect": [
                    "warn",
                    {
                        "assertFunctionNames": ["expect**"],
                    },
                ],
                "jest/prefer-expect-resolves": "error",
                "jest/prefer-hooks-on-top": "error",
                "jest/prefer-strict-equal": "off",
                "jest/valid-title": "off",
                "jest/padding-around-after-all-blocks": "error",
            },
        },
        {
            "files": ["tests/**/*"],
            "rules": {
                "playwright/expect-expect": "warn",
                "playwright/max-nested-describe": "warn",
                "playwright/missing-playwright-await": "error",
                "playwright/no-conditional-expect": "warn",
                "playwright/no-conditional-in-test": "warn",
                "playwright/no-element-handle": "warn",
                "playwright/no-eval": "warn",
                "playwright/no-focused-test": "error",
                "playwright/no-force-option": "warn",
                "playwright/no-nested-step": "warn",
                "playwright/no-networkidle": "error",
                "playwright/no-page-pause": "warn",
                "playwright/no-skipped-test": "warn",
                "playwright/no-standalone-expect": "error",
                "playwright/no-unsafe-references": "error",
                "playwright/no-useless-await": "warn",
                "playwright/no-useless-not": "warn",
                "playwright/no-wait-for-selector": "warn",
                "playwright/no-wait-for-timeout": "warn",
                "playwright/prefer-web-first-assertions": "error",
                "playwright/valid-describe-callback": "error",
                "playwright/valid-expect": "error",
                "playwright/valid-expect-in-promise": "error",
                "playwright/valid-title": "error",
                "playwright/prefer-to-have-length": "error",
            },
            "jsPlugins": ["eslint-plugin-playwright"],
            "globals": {
                "AbortController": "readonly",
                "AbortSignal": "readonly",
                "atob": "readonly",
                "Blob": "readonly",
                "BroadcastChannel": "readonly",
                "btoa": "readonly",
                "ByteLengthQueuingStrategy": "readonly",
                "clearInterval": "readonly",
                "clearTimeout": "readonly",
                "CompressionStream": "readonly",
                "console": "readonly",
                "CountQueuingStrategy": "readonly",
                "crypto": "readonly",
                "Crypto": "readonly",
                "CryptoKey": "readonly",
                "CustomEvent": "readonly",
                "DecompressionStream": "readonly",
                "DOMException": "readonly",
                "Event": "readonly",
                "EventTarget": "readonly",
                "fetch": "readonly",
                "File": "readonly",
                "FormData": "readonly",
                "Headers": "readonly",
                "Intl": "readonly",
                "MessageChannel": "readonly",
                "MessageEvent": "readonly",
                "MessagePort": "readonly",
                "performance": "readonly",
                "PerformanceEntry": "readonly",
                "PerformanceMark": "readonly",
                "PerformanceMeasure": "readonly",
                "PerformanceObserver": "readonly",
                "PerformanceObserverEntryList": "readonly",
                "PerformanceResourceTiming": "readonly",
                "queueMicrotask": "readonly",
                "ReadableByteStreamController": "readonly",
                "ReadableStream": "readonly",
                "ReadableStreamBYOBReader": "readonly",
                "ReadableStreamBYOBRequest": "readonly",
                "ReadableStreamDefaultController": "readonly",
                "ReadableStreamDefaultReader": "readonly",
                "Request": "readonly",
                "Response": "readonly",
                "setInterval": "readonly",
                "setTimeout": "readonly",
                "structuredClone": "readonly",
                "SubtleCrypto": "readonly",
                "TextDecoder": "readonly",
                "TextDecoderStream": "readonly",
                "TextEncoder": "readonly",
                "TextEncoderStream": "readonly",
                "TransformStream": "readonly",
                "TransformStreamDefaultController": "readonly",
                "URL": "readonly",
                "URLSearchParams": "readonly",
                "WebAssembly": "readonly",
                "WritableStream": "readonly",
                "WritableStreamDefaultController": "readonly",
                "WritableStreamDefaultWriter": "readonly",
            },
        },
    ],
});
