import { defineConfig } from "oxlint";

export default defineConfig({
  "plugins": [
    "typescript",
    "jsdoc",
    "react",
    "jest",
    "unicorn",
    "jsx-a11y",
    "import"
  ],
  "jsPlugins": [
    "eslint-plugin-react-compiler",
    "eslint-plugin-sonarjs"
  ],
  "categories": {
    "correctness": "off"
  },
  "env": {
    "builtin": true,
    "browser": true,
    "es2026": true,
    "jest": true,
    "node": true
  },
  "settings": {
    "react": {
      "version": "999.999.999"
    }
  },
  "ignorePatterns": [
    "./**/*.js",
    "./**/*.cjs",
    "./**/*.mjs",
    "./**/*.d.ts",
    "**/proto/*.ts"
  ],
  "rules": {
    "constructor-super": "error",
    "for-direction": "error",
    "no-async-promise-executor": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "error",
    "no-empty-pattern": "off",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "error",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-array": "off",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-prototype-builtins": "error",
    "no-redeclare": "error",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unexpected-multiline": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
      "error",
      {
        "argsIgnorePattern": "_",
        "varsIgnorePattern": "_",
        "caughtErrorsIgnorePattern": "_",
        "args": "after-used",
        "ignoreRestSiblings": false
      }
    ],
    "no-useless-backreference": "error",
    "no-useless-catch": "error",
    "no-useless-escape": "error",
    "no-with": "error",
    "require-yield": "error",
    "use-isnan": "error",
    "valid-typeof": "error",
    "no-self-compare": "error",
    "default-case-last": "error",
    "eqeqeq": "error",
    "no-else-return": "error",
    "no-useless-return": "error",
    "no-var": "error",
    "no-console": [
      "error",
      {
        "allow": [
          "warn",
          "error"
        ]
      }
    ],
    "prefer-const": "error",
    "no-array-constructor": "error",
    "arrow-body-style": "error",
    "no-unused-expressions": "off",
    "jsdoc/check-access": "error",
    "jsdoc/check-property-names": "error",
    "jsdoc/check-tag-names": [
      "error",
      {
        "jsxTags": true
      }
    ],
    "jsdoc/empty-tags": "error",
    "jsdoc/require-param-description": "error",
    "jsdoc/require-param-name": "error",
    "jsdoc/require-param": "error",
    "jsdoc/require-property": "error",
    "jsdoc/require-property-description": "error",
    "jsdoc/require-property-name": "error",
    "jsdoc/require-returns-description": "error",
    "jsdoc/require-returns": "error",
    "jsdoc/require-yields": "error",
    "react/display-name": "error",
    "react/jsx-key": "error",
    "react/jsx-no-comment-textnodes": "error",
    "react/jsx-no-duplicate-props": "error",
    "react/jsx-no-target-blank": "error",
    "react/jsx-no-undef": "error",
    "react/no-children-prop": "error",
    "react/no-danger-with-children": "error",
    "react/no-direct-mutation-state": "error",
    "react/no-find-dom-node": "error",
    "react/no-is-mounted": "error",
    "react/no-render-return-value": "error",
    "react/no-string-refs": "error",
    "react/no-unescaped-entities": "error",
    "react/no-unknown-property": "error",
    "react-compiler/react-compiler": "error",
    "jest/expect-expect": "warn",
    "jest/no-alias-methods": "warn",
    "jest/no-commented-out-tests": "warn",
    "jest/no-conditional-expect": "error",
    "jest/no-deprecated-functions": "error",
    "jest/no-disabled-tests": "warn",
    "jest/no-done-callback": "error",
    "jest/no-export": "error",
    "jest/no-focused-tests": "error",
    "jest/no-identical-title": "error",
    "jest/no-interpolation-in-snapshots": "error",
    "jest/no-jasmine-globals": "error",
    "jest/no-mocks-import": "error",
    "jest/no-standalone-expect": "error",
    "jest/no-test-prefixes": "error",
    "jest/valid-describe-callback": "error",
    "jest/valid-expect": "error",
    "jest/valid-title": "error",
    "jest/prefer-to-be": "error",
    "jest/prefer-to-contain": "error",
    "jest/prefer-to-have-length": "error",
    "unicorn/catch-error-name": [
      "error",
      {
        "name": "e"
      }
    ],
    "unicorn/consistent-assert": "error",
    "unicorn/consistent-date-clone": "error",
    "unicorn/consistent-empty-array-spread": "error",
    "unicorn/consistent-existence-index-check": "error",
    "unicorn/custom-error-definition": "error",
    "unicorn/empty-brace-spaces": "error",
    "unicorn/error-message": "error",
    "unicorn/escape-case": "error",
    "unicorn/explicit-length-check": "error",
    "unicorn/filename-case": [
      "error",
      {
        "cases": {
          "camelCase": true,
          "pascalCase": true
        },
        "ignore": [
          {}
        ]
      }
    ],
    "unicorn/new-for-builtins": "error",
    "unicorn/no-abusive-eslint-disable": "error",
    "unicorn/no-accessor-recursion": "error",
    "unicorn/no-anonymous-default-export": "error",
    "unicorn/no-array-method-this-argument": "error",
    "unicorn/no-await-expression-member": "error",
    "unicorn/no-await-in-promise-methods": "error",
    "unicorn/no-console-spaces": "error",
    "unicorn/no-document-cookie": "error",
    "unicorn/no-empty-file": "error",
    "unicorn/no-hex-escape": "error",
    "unicorn/no-instanceof-builtins": "error",
    "unicorn/no-invalid-fetch-options": "error",
    "unicorn/no-invalid-remove-event-listener": "error",
    "unicorn/no-lonely-if": "error",
    "unicorn/no-magic-array-flat-depth": "error",
    "unicorn/no-negated-condition": "error",
    "unicorn/no-negation-in-equality-check": "error",
    "unicorn/no-new-buffer": "error",
    "unicorn/no-null": "error",
    "unicorn/no-process-exit": "error",
    "unicorn/no-single-promise-in-promise-methods": "error",
    "unicorn/no-static-only-class": "error",
    "unicorn/no-thenable": "error",
    "unicorn/no-this-assignment": "error",
    "unicorn/no-typeof-undefined": "error",
    "unicorn/no-unnecessary-array-flat-depth": "error",
    "unicorn/no-unnecessary-array-splice-count": "error",
    "unicorn/no-unnecessary-await": "error",
    "unicorn/no-unnecessary-slice-end": "error",
    "unicorn/no-unreadable-array-destructuring": "error",
    "unicorn/no-unreadable-iife": "error",
    "unicorn/no-useless-fallback-in-spread": "error",
    "unicorn/no-useless-length-check": "error",
    "unicorn/no-useless-promise-resolve-reject": "error",
    "unicorn/no-useless-spread": "error",
    "unicorn/no-useless-switch-case": "error",
    "unicorn/no-useless-undefined": [
      "error",
      {
        "checkArguments": false
      }
    ],
    "unicorn/no-zero-fractions": "error",
    "unicorn/number-literal-case": "error",
    "unicorn/numeric-separators-style": "error",
    "unicorn/prefer-add-event-listener": "error",
    "unicorn/prefer-array-find": "error",
    "unicorn/prefer-array-flat-map": "error",
    "unicorn/prefer-array-flat": "error",
    "unicorn/prefer-array-index-of": "error",
    "unicorn/prefer-array-some": "error",
    "unicorn/prefer-at": "error",
    "unicorn/prefer-blob-reading-methods": "error",
    "unicorn/prefer-code-point": "error",
    "unicorn/prefer-date-now": "error",
    "unicorn/prefer-default-parameters": "error",
    "unicorn/prefer-dom-node-append": "error",
    "unicorn/prefer-dom-node-dataset": "error",
    "unicorn/prefer-dom-node-remove": "error",
    "unicorn/prefer-dom-node-text-content": "error",
    "unicorn/prefer-event-target": "error",
    "unicorn/prefer-includes": "error",
    "unicorn/prefer-keyboard-event-key": "error",
    "unicorn/prefer-logical-operator-over-ternary": "error",
    "unicorn/prefer-math-min-max": "error",
    "unicorn/prefer-modern-dom-apis": "error",
    "unicorn/prefer-modern-math-apis": "error",
    "unicorn/prefer-module": "error",
    "unicorn/prefer-native-coercion-functions": "error",
    "unicorn/prefer-negative-index": "error",
    "unicorn/prefer-node-protocol": "error",
    "unicorn/prefer-object-from-entries": "error",
    "unicorn/prefer-optional-catch-binding": "error",
    "unicorn/prefer-prototype-methods": "error",
    "unicorn/prefer-reflect-apply": "error",
    "unicorn/prefer-regexp-test": "error",
    "unicorn/prefer-set-has": "error",
    "unicorn/prefer-set-size": "error",
    "unicorn/prefer-spread": "error",
    "unicorn/prefer-string-raw": "error",
    "unicorn/prefer-string-replace-all": "error",
    "unicorn/prefer-string-slice": "error",
    "unicorn/prefer-string-starts-ends-with": "error",
    "unicorn/prefer-string-trim-start-end": "error",
    "unicorn/prefer-structured-clone": "error",
    "unicorn/prefer-ternary": [
      "error",
      "only-single-line"
    ],
    "unicorn/prefer-type-error": "error",
    "unicorn/relative-url-style": "error",
    "unicorn/require-array-join-separator": "error",
    "unicorn/require-number-to-fixed-digits-argument": "error",
    "unicorn/text-encoding-identifier-case": "error",
    "unicorn/throw-new-error": "error",
    "sonarjs/class-name": "error",
    "sonarjs/no-fallthrough": "error",
    "sonarjs/no-equals-in-for-termination": "error",
    "sonarjs/no-extra-arguments": "error",
    "sonarjs/no-labels": "error",
    "sonarjs/no-nested-assignment": "error",
    "sonarjs/no-redundant-boolean": "error",
    "sonarjs/prefer-single-boolean-return": "error",
    "sonarjs/unused-import": "error",
    "sonarjs/fixme-tag": "error",
    "sonarjs/no-case-label-in-switch": "error",
    "sonarjs/no-parameter-reassignment": "error",
    "sonarjs/prefer-while": "error",
    "sonarjs/no-small-switch": "error",
    "sonarjs/no-hardcoded-ip": "error",
    "sonarjs/label-position": "error",
    "sonarjs/public-static-readonly": "error",
    "sonarjs/call-argument-line": "error",
    "sonarjs/max-switch-cases": "error",
    "sonarjs/function-inside-loop": "error",
    "sonarjs/code-eval": "error",
    "sonarjs/future-reserved-words": "error",
    "sonarjs/bitwise-operators": "error",
    "sonarjs/no-primitive-wrappers": "error",
    "sonarjs/no-skipped-tests": "error",
    "sonarjs/no-one-iteration-loop": "error",
    "sonarjs/no-identical-expressions": "error",
    "sonarjs/constructor-for-side-effects": "error",
    "sonarjs/no-dead-store": "error",
    "sonarjs/no-identical-conditions": "error",
    "sonarjs/no-duplicated-branches": "error",
    "sonarjs/deprecation": "error",
    "sonarjs/no-inverted-boolean-check": "error",
    "sonarjs/misplaced-loop-counter": "error",
    "sonarjs/no-nested-functions": "error",
    "sonarjs/no-hardcoded-passwords": "error",
    "sonarjs/sql-queries": "error",
    "sonarjs/insecure-cookie": "error",
    "sonarjs/no-useless-increment": "error",
    "sonarjs/no-globals-shadowing": "error",
    "sonarjs/no-empty-test-file": "error",
    "sonarjs/no-ignored-return": "error",
    "sonarjs/arguments-order": "error",
    "sonarjs/pseudo-random": "error",
    "sonarjs/for-loop-increment-sign": "error",
    "sonarjs/null-dereference": "error",
    "sonarjs/no-selector-parameter": "error",
    "sonarjs/updated-loop-counter": "error",
    "sonarjs/block-scoped-var": "error",
    "sonarjs/no-ignored-exceptions": "error",
    "sonarjs/no-gratuitous-expressions": "error",
    "sonarjs/file-uploads": "error",
    "sonarjs/file-permissions": "error",
    "sonarjs/no-empty-character-class": "error",
    "sonarjs/no-unenclosed-multiline-block": "error",
    "sonarjs/index-of-compare-to-positive-number": "error",
    "sonarjs/assertions-in-tests": "error",
    "sonarjs/no-implicit-global": "error",
    "sonarjs/no-useless-catch": "error",
    "sonarjs/xml-parser-xxe": "error",
    "sonarjs/non-existent-operator": "error",
    "sonarjs/post-message": "error",
    "sonarjs/no-array-delete": "error",
    "sonarjs/no-alphabetical-sort": "error",
    "sonarjs/no-incomplete-assertions": "error",
    "sonarjs/no-global-this": "error",
    "sonarjs/new-operator-misuse": "error",
    "sonarjs/no-delete-var": "error",
    "sonarjs/cookie-no-httponly": "error",
    "sonarjs/no-nested-conditional": "error",
    "sonarjs/different-types-comparison": "error",
    "sonarjs/inverted-assertion-arguments": "error",
    "sonarjs/updated-const-var": "error",
    "sonarjs/no-invariant-returns": "error",
    "sonarjs/generator-without-yield": "error",
    "sonarjs/no-associative-arrays": "error",
    "sonarjs/comma-or-logical-or-case": "error",
    "sonarjs/no-redundant-jump": "error",
    "sonarjs/inconsistent-function-call": "error",
    "sonarjs/no-use-of-empty-return-value": "error",
    "sonarjs/void-use": "error",
    "sonarjs/argument-type": "error",
    "sonarjs/in-operator-type-error": "error",
    "sonarjs/array-callback-without-return": "error",
    "sonarjs/function-return-type": "error",
    "sonarjs/super-invocation": "error",
    "sonarjs/no-all-duplicated-branches": "error",
    "sonarjs/no-same-line-conditional": "error",
    "sonarjs/no-collection-size-mischeck": "error",
    "sonarjs/no-unthrown-error": "error",
    "sonarjs/no-unused-collection": "error",
    "sonarjs/no-os-command-from-path": "error",
    "sonarjs/no-misleading-array-reverse": "error",
    "sonarjs/no-element-overwrite": "error",
    "sonarjs/no-identical-functions": "error",
    "sonarjs/no-empty-collection": "error",
    "sonarjs/no-redundant-assignments": "error",
    "sonarjs/prefer-type-guard": "error",
    "sonarjs/use-type-alias": "error",
    "sonarjs/no-useless-intersection": "error",
    "sonarjs/weak-ssl": "error",
    "sonarjs/no-weak-keys": "error",
    "sonarjs/csrf": "error",
    "sonarjs/production-debug": "error",
    "sonarjs/prefer-default-last": "error",
    "sonarjs/no-in-misuse": "error",
    "sonarjs/no-duplicate-in-composite": "error",
    "sonarjs/no-undefined-argument": "error",
    "sonarjs/no-nested-template-literals": "error",
    "sonarjs/prefer-promise-shorthand": "error",
    "sonarjs/os-command": "error",
    "sonarjs/no-redundant-optional": "error",
    "sonarjs/hashing": "error",
    "sonarjs/no-try-promise": "error",
    "sonarjs/unverified-certificate": "error",
    "sonarjs/no-unsafe-unzip": "error",
    "sonarjs/cors": "error",
    "sonarjs/link-with-target-blank": "error",
    "sonarjs/disabled-auto-escaping": "error",
    "sonarjs/table-header": "error",
    "sonarjs/no-table-as-layout": "error",
    "sonarjs/table-header-reference": "error",
    "sonarjs/object-alt-content": "error",
    "sonarjs/no-clear-text-protocols": "error",
    "sonarjs/publicly-writable-directories": "error",
    "sonarjs/unverified-hostname": "error",
    "sonarjs/encryption-secure-mode": "error",
    "sonarjs/no-weak-cipher": "error",
    "sonarjs/no-intrusive-permissions": "error",
    "sonarjs/insecure-jwt-token": "error",
    "sonarjs/x-powered-by": "error",
    "sonarjs/hidden-files": "error",
    "sonarjs/content-length": "error",
    "sonarjs/disabled-resource-integrity": "error",
    "sonarjs/content-security-policy": "error",
    "sonarjs/no-mixed-content": "error",
    "sonarjs/frame-ancestors": "error",
    "sonarjs/no-mime-sniff": "error",
    "sonarjs/no-referrer-policy": "error",
    "sonarjs/strict-transport-security": "error",
    "sonarjs/confidential-information-logging": "error",
    "sonarjs/no-ip-forward": "error",
    "sonarjs/empty-string-repetition": "error",
    "sonarjs/regex-complexity": "error",
    "sonarjs/anchor-precedence": "error",
    "sonarjs/slow-regex": "error",
    "sonarjs/no-invalid-regexp": "error",
    "sonarjs/unused-named-groups": "error",
    "sonarjs/no-same-argument-assert": "error",
    "sonarjs/no-misleading-character-class": "error",
    "sonarjs/duplicates-in-character-class": "error",
    "sonarjs/session-regeneration": "error",
    "sonarjs/test-check-exception": "error",
    "sonarjs/stable-tests": "error",
    "sonarjs/no-empty-after-reluctant": "error",
    "sonarjs/single-character-alternation": "error",
    "sonarjs/no-code-after-done": "error",
    "sonarjs/disabled-timeout": "error",
    "sonarjs/chai-determinate-assertion": "error",
    "sonarjs/aws-s3-bucket-insecure-http": "error",
    "sonarjs/aws-s3-bucket-versioning": "error",
    "sonarjs/aws-s3-bucket-granted-access": "error",
    "sonarjs/no-angular-bypass-sanitization": "error",
    "sonarjs/aws-iam-public-access": "error",
    "sonarjs/aws-ec2-unencrypted-ebs-volume": "error",
    "sonarjs/aws-s3-bucket-public-access": "error",
    "sonarjs/aws-iam-all-privileges": "error",
    "sonarjs/aws-rds-unencrypted-databases": "error",
    "sonarjs/aws-opensearchservice-domain": "error",
    "sonarjs/aws-iam-privilege-escalation": "error",
    "sonarjs/aws-sagemaker-unencrypted-notebook": "error",
    "sonarjs/aws-restricted-ip-admin-access": "error",
    "sonarjs/no-empty-alternatives": "error",
    "sonarjs/no-control-regex": "error",
    "sonarjs/no-regex-spaces": "error",
    "sonarjs/aws-sns-unencrypted-topics": "error",
    "sonarjs/existing-groups": "error",
    "sonarjs/aws-ec2-rds-dms-public": "error",
    "sonarjs/aws-sqs-unencrypted-queue": "error",
    "sonarjs/no-empty-group": "error",
    "sonarjs/aws-efs-unencrypted": "error",
    "sonarjs/aws-apigateway-public-api": "error",
    "sonarjs/stateful-regex": "error",
    "sonarjs/concise-regex": "error",
    "sonarjs/single-char-in-character-classes": "error",
    "sonarjs/no-hardcoded-secrets": "error",
    "sonarjs/no-exclusive-tests": "error",
    "sonarjs/jsx-no-leaked-render": "error",
    "sonarjs/no-hook-setter-in-body": "error",
    "sonarjs/no-useless-react-setstate": "error",
    "sonarjs/no-uniq-key": "error",
    "sonarjs/redundant-type-aliases": "error",
    "sonarjs/prefer-regexp-exec": "error",
    "sonarjs/no-internal-api-use": "error",
    "sonarjs/prefer-read-only-props": "error",
    "sonarjs/no-literal-call": "error",
    "sonarjs/reduce-initial-value": "error",
    "sonarjs/no-async-constructor": "error",
    "jsx-a11y/autocomplete-valid": [
      "warn",
      {
        "inputComponents": [
          "InputField"
        ]
      }
    ],
    "jsx-a11y/lang": "warn",
    "jsx-a11y/alt-text": "warn",
    "jsx-a11y/anchor-has-content": "warn",
    "jsx-a11y/anchor-is-valid": "warn",
    "jsx-a11y/aria-activedescendant-has-tabindex": "warn",
    "jsx-a11y/aria-props": "warn",
    "jsx-a11y/aria-proptypes": "warn",
    "jsx-a11y/aria-role": "warn",
    "jsx-a11y/aria-unsupported-elements": "warn",
    "jsx-a11y/heading-has-content": "warn",
    "jsx-a11y/html-has-lang": "warn",
    "jsx-a11y/iframe-has-title": "warn",
    "jsx-a11y/img-redundant-alt": "warn",
    "jsx-a11y/media-has-caption": "warn",
    "jsx-a11y/mouse-events-have-key-events": "warn",
    "jsx-a11y/no-access-key": "warn",
    "jsx-a11y/no-autofocus": "warn",
    "jsx-a11y/no-distracting-elements": "warn",
    "jsx-a11y/no-noninteractive-tabindex": "warn",
    "jsx-a11y/no-redundant-roles": "warn",
    "jsx-a11y/no-static-element-interactions": "warn",
    "jsx-a11y/role-has-required-aria-props": "warn",
    "jsx-a11y/role-supports-aria-props": "warn",
    "jsx-a11y/scope": "warn",
    "jsx-a11y/tabindex-no-positive": "warn",
    "import/namespace": "error",
    "import/default": "error",
    "import/no-named-as-default": "warn",
    "import/no-named-as-default-member": "warn",
    "import/no-duplicates": "error",
    "import/no-self-import": "error",
    "import/no-mutable-exports": "error",
    "import/first": "error",
    "import/extensions": [
      "error",
      "ignorePackages",
      {
        "ts": "never",
        "tsx": "never"
      }
    ],
    "import/no-cycle": "error",
    "react/rules-of-hooks": "error",
    "react/exhaustive-deps": "warn",
    "typescript/ban-ts-comment": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-this-alias": "error",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/triple-slash-reference": "error",
    "typescript/array-type": [
      "error",
      {
        "default": "array-simple"
      }
    ],
    "typescript/no-restricted-types": [
      "error",
      {
        "types": {
          "null": {
            "message": "Use undefined instead",
            "fixWith": "undefined"
          }
        }
      }
    ],
    "typescript/no-inferrable-types": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/no-var-requires": "error"
  },
  "overrides": [
    {
      "files": [
        "scripts/**"
      ],
      "rules": {
        "no-console": "off"
      }
    },
    {
      "files": [
        "**/*.ts",
        "**/*.tsx",
        "**/*.mts",
        "**/*.cts"
      ],
      "rules": {
        "constructor-super": "off",
        "no-class-assign": "off",
        "no-const-assign": "off",
        "no-dupe-class-members": "off",
        "no-dupe-keys": "off",
        "no-func-assign": "off",
        "no-import-assign": "off",
        "no-new-native-nonconstructor": "off",
        "no-obj-calls": "off",
        "no-redeclare": "off",
        "no-setter-return": "off",
        "no-this-before-super": "off",
        "no-unsafe-negation": "off",
        "no-with": "off",
        "prefer-rest-params": "error",
        "prefer-spread": "error"
      }
    },
    {
      "files": [
        "src/**/*.tsx"
      ],
      "rules": {
        "react/button-has-type": "error",
        "react/forbid-elements": [
          "error",
          {
            "forbid": [
              {
                "element": "input",
                "message": "use <InputField> instead"
              }
            ]
          }
        ],
        "react/hook-use-state": "off",
        "react/no-danger": "error",
        "react/no-did-mount-set-state": "error",
        "react/no-multi-comp": "off",
        "react/no-namespace": "error",
        "react/no-redundant-should-component-update": "error",
        "react/no-this-in-sfc": "error",
        "react/no-unsafe": "error",
        "react/no-will-update-set-state": "error",
        "react/self-closing-comp": [
          "error",
          {
            "component": true,
            "html": false
          }
        ],
        "react/style-prop-object": "error",
        "react/void-dom-elements-no-children": "error",
        "react/jsx-boolean-value": [
          "error",
          "never"
        ],
        "react/jsx-curly-brace-presence": [
          "error",
          {
            "props": "never",
            "children": "never",
            "propElementValues": "always"
          }
        ],
        "react/jsx-filename-extension": [
          "error",
          {
            "extensions": [
              ".tsx"
            ]
          }
        ],
        "react/jsx-fragments": [
          "error",
          "syntax"
        ],
        "react/jsx-handler-names": "error",
        "react/jsx-no-constructed-context-values": "error",
        "react/jsx-no-script-url": "error",
        "react/jsx-no-useless-fragment": "error",
        "react/jsx-pascal-case": "error",
        "react/no-unknown-property": [
          "error",
          {
            "ignore": [
              "unselectable"
            ]
          }
        ]
      },
      "jsPlugins": [
        "eslint-plugin-react-compiler"
      ]
    },
    {
      "files": [
        "src/**/*.test.ts"
      ],
      "rules": {
        "jest/no-commented-out-tests": "off",
        "jest/prefer-comparison-matcher": "error",
        "jest/prefer-equality-matcher": "error",
        "jest/expect-expect": [
          "warn",
          {
            "assertFunctionNames": [
              "expect**"
            ]
          }
        ],
        "jest/prefer-expect-resolves": "error",
        "jest/prefer-hooks-on-top": "error",
        "jest/prefer-strict-equal": "off",
        "jest/valid-title": "off",
        "jest/padding-around-after-all-blocks": "error"
      }
    },
    {
      "files": [
        "**/*.{test,spec}.ts?(x)"
      ],
      "rules": {
        "sonarjs/no-identical-functions": "off",
        "sonarjs/no-dead-store": "off"
      },
      "jsPlugins": [
        "eslint-plugin-sonarjs"
      ]
    },
    {
      "files": [
        "tests/**/*"
      ],
      "rules": {
        "playwright/expect-expect": "warn",
        "playwright/max-nested-describe": "warn",
        "playwright/missing-playwright-await": "error",
        "playwright/no-conditional-expect": "warn",
        "playwright/no-conditional-in-test": "warn",
        "playwright/no-element-handle": "warn",
        "playwright/no-eval": "warn",
        "playwright/no-focused-test": "error",
        "playwright/no-force-option": "warn",
        "playwright/no-nested-step": "warn",
        "playwright/no-networkidle": "error",
        "playwright/no-page-pause": "warn",
        "playwright/no-skipped-test": "warn",
        "playwright/no-standalone-expect": "error",
        "playwright/no-unsafe-references": "error",
        "playwright/no-useless-await": "warn",
        "playwright/no-useless-not": "warn",
        "playwright/no-wait-for-selector": "warn",
        "playwright/no-wait-for-timeout": "warn",
        "playwright/prefer-web-first-assertions": "error",
        "playwright/valid-describe-callback": "error",
        "playwright/valid-expect": "error",
        "playwright/valid-expect-in-promise": "error",
        "playwright/valid-title": "error",
        "playwright/prefer-to-have-length": "error"
      },
      "jsPlugins": [
        "eslint-plugin-playwright"
      ],
      "globals": {
        "AbortController": "readonly",
        "AbortSignal": "readonly",
        "atob": "readonly",
        "Blob": "readonly",
        "BroadcastChannel": "readonly",
        "btoa": "readonly",
        "ByteLengthQueuingStrategy": "readonly",
        "clearInterval": "readonly",
        "clearTimeout": "readonly",
        "CompressionStream": "readonly",
        "console": "readonly",
        "CountQueuingStrategy": "readonly",
        "crypto": "readonly",
        "Crypto": "readonly",
        "CryptoKey": "readonly",
        "CustomEvent": "readonly",
        "DecompressionStream": "readonly",
        "DOMException": "readonly",
        "Event": "readonly",
        "EventTarget": "readonly",
        "fetch": "readonly",
        "File": "readonly",
        "FormData": "readonly",
        "Headers": "readonly",
        "Intl": "readonly",
        "MessageChannel": "readonly",
        "MessageEvent": "readonly",
        "MessagePort": "readonly",
        "performance": "readonly",
        "PerformanceEntry": "readonly",
        "PerformanceMark": "readonly",
        "PerformanceMeasure": "readonly",
        "PerformanceObserver": "readonly",
        "PerformanceObserverEntryList": "readonly",
        "PerformanceResourceTiming": "readonly",
        "queueMicrotask": "readonly",
        "ReadableByteStreamController": "readonly",
        "ReadableStream": "readonly",
        "ReadableStreamBYOBReader": "readonly",
        "ReadableStreamBYOBRequest": "readonly",
        "ReadableStreamDefaultController": "readonly",
        "ReadableStreamDefaultReader": "readonly",
        "Request": "readonly",
        "Response": "readonly",
        "setInterval": "readonly",
        "setTimeout": "readonly",
        "structuredClone": "readonly",
        "SubtleCrypto": "readonly",
        "TextDecoder": "readonly",
        "TextDecoderStream": "readonly",
        "TextEncoder": "readonly",
        "TextEncoderStream": "readonly",
        "TransformStream": "readonly",
        "TransformStreamDefaultController": "readonly",
        "URL": "readonly",
        "URLSearchParams": "readonly",
        "WebAssembly": "readonly",
        "WritableStream": "readonly",
        "WritableStreamDefaultController": "readonly",
        "WritableStreamDefaultWriter": "readonly"
      }
    }
  ]

});
