// flow-typed signature: 2b86754277a0361dc647a5b3b52e163b
// flow-typed version: <<STUB>>/gulp-uglify-es_v^0.1.4/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-uglify-es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-uglify-es' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-uglify-es/lib/index' {
  declare module.exports: any;
}

declare module 'gulp-uglify-es/lib/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-uglify-es/lib/index.js' {
  declare module.exports: $Exports<'gulp-uglify-es/lib/index'>;
}
declare module 'gulp-uglify-es/lib/index.test.js' {
  declare module.exports: $Exports<'gulp-uglify-es/lib/index.test'>;
}
