// flow-typed signature: 4d01dfbd847c5a2ace2d48aeb43db0ef
// flow-typed version: <<STUB>>/gulp-add-src_v^1.0.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-add-src'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-add-src' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-add-src/index' {
  declare module.exports: $Exports<'gulp-add-src'>;
}
declare module 'gulp-add-src/index.js' {
  declare module.exports: $Exports<'gulp-add-src'>;
}
