// flow-typed signature: cb9624bd8d3add70e76998c5b1fa0993
// flow-typed version: <<STUB>>/gulp-append-prepend_v^1.0.4/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-append-prepend'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-append-prepend' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-append-prepend/index' {
  declare module.exports: $Exports<'gulp-append-prepend'>;
}
declare module 'gulp-append-prepend/index.js' {
  declare module.exports: $Exports<'gulp-append-prepend'>;
}
