// flow-typed signature: a8dd1eb47df8c47ec831b2149bc3e997
// flow-typed version: <<STUB>>/npm_v^6.4.0/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm/bin/npm-cli' {
  declare module.exports: any;
}

declare module 'npm/bin/npx-cli' {
  declare module.exports: any;
}

declare module 'npm/html/static/toc' {
  declare module.exports: any;
}

declare module 'npm/lib/access' {
  declare module.exports: any;
}

declare module 'npm/lib/adduser' {
  declare module.exports: any;
}

declare module 'npm/lib/audit' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/legacy' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/oauth' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/saml' {
  declare module.exports: any;
}

declare module 'npm/lib/auth/sso' {
  declare module.exports: any;
}

declare module 'npm/lib/bin' {
  declare module.exports: any;
}

declare module 'npm/lib/bugs' {
  declare module.exports: any;
}

declare module 'npm/lib/build' {
  declare module.exports: any;
}

declare module 'npm/lib/cache' {
  declare module.exports: any;
}

declare module 'npm/lib/ci' {
  declare module.exports: any;
}

declare module 'npm/lib/completion' {
  declare module.exports: any;
}

declare module 'npm/lib/config' {
  declare module.exports: any;
}

declare module 'npm/lib/config/bin-links' {
  declare module.exports: any;
}

declare module 'npm/lib/config/clear-credentials-by-uri' {
  declare module.exports: any;
}

declare module 'npm/lib/config/cmd-list' {
  declare module.exports: any;
}

declare module 'npm/lib/config/core' {
  declare module.exports: any;
}

declare module 'npm/lib/config/defaults' {
  declare module.exports: any;
}

declare module 'npm/lib/config/fetch-opts' {
  declare module.exports: any;
}

declare module 'npm/lib/config/gentle-fs' {
  declare module.exports: any;
}

declare module 'npm/lib/config/get-credentials-by-uri' {
  declare module.exports: any;
}

declare module 'npm/lib/config/lifecycle' {
  declare module.exports: any;
}

declare module 'npm/lib/config/load-cafile' {
  declare module.exports: any;
}

declare module 'npm/lib/config/load-prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/config/load-uid' {
  declare module.exports: any;
}

declare module 'npm/lib/config/nerf-dart' {
  declare module.exports: any;
}

declare module 'npm/lib/config/pacote' {
  declare module.exports: any;
}

declare module 'npm/lib/config/reg-client' {
  declare module.exports: any;
}

declare module 'npm/lib/config/set-credentials-by-uri' {
  declare module.exports: any;
}

declare module 'npm/lib/config/set-user' {
  declare module.exports: any;
}

declare module 'npm/lib/dedupe' {
  declare module.exports: any;
}

declare module 'npm/lib/deprecate' {
  declare module.exports: any;
}

declare module 'npm/lib/dist-tag' {
  declare module.exports: any;
}

declare module 'npm/lib/docs' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor/check-files-permission' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor/check-ping' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor/get-git-path' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor/get-latest-nodejs-version' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor/get-latest-npm-version' {
  declare module.exports: any;
}

declare module 'npm/lib/doctor/verify-cached-files' {
  declare module.exports: any;
}

declare module 'npm/lib/edit' {
  declare module.exports: any;
}

declare module 'npm/lib/explore' {
  declare module.exports: any;
}

declare module 'npm/lib/fetch-package-metadata' {
  declare module.exports: any;
}

declare module 'npm/lib/get' {
  declare module.exports: any;
}

declare module 'npm/lib/help-search' {
  declare module.exports: any;
}

declare module 'npm/lib/help' {
  declare module.exports: any;
}

declare module 'npm/lib/hook' {
  declare module.exports: any;
}

declare module 'npm/lib/init' {
  declare module.exports: any;
}

declare module 'npm/lib/install-ci-test' {
  declare module.exports: any;
}

declare module 'npm/lib/install-test' {
  declare module.exports: any;
}

declare module 'npm/lib/install' {
  declare module.exports: any;
}

declare module 'npm/lib/install/access-error' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/build' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/extract-worker' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/extract' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/fetch' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/finalize' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/global-install' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/global-link' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/install' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/move' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/postinstall' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/preinstall' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/prepare' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/refresh-package-json' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/remove' {
  declare module.exports: any;
}

declare module 'npm/lib/install/action/unbuild' {
  declare module.exports: any;
}

declare module 'npm/lib/install/actions' {
  declare module.exports: any;
}

declare module 'npm/lib/install/and-add-parent-to-errors' {
  declare module.exports: any;
}

declare module 'npm/lib/install/and-finish-tracker' {
  declare module.exports: any;
}

declare module 'npm/lib/install/and-ignore-errors' {
  declare module.exports: any;
}

declare module 'npm/lib/install/audit' {
  declare module.exports: any;
}

declare module 'npm/lib/install/check-permissions' {
  declare module.exports: any;
}

declare module 'npm/lib/install/copy-tree' {
  declare module.exports: any;
}

declare module 'npm/lib/install/decompose-actions' {
  declare module.exports: any;
}

declare module 'npm/lib/install/deps' {
  declare module.exports: any;
}

declare module 'npm/lib/install/diff-trees' {
  declare module.exports: any;
}

declare module 'npm/lib/install/exists' {
  declare module.exports: any;
}

declare module 'npm/lib/install/flatten-tree' {
  declare module.exports: any;
}

declare module 'npm/lib/install/get-requested' {
  declare module.exports: any;
}

declare module 'npm/lib/install/has-modern-meta' {
  declare module.exports: any;
}

declare module 'npm/lib/install/inflate-bundled' {
  declare module.exports: any;
}

declare module 'npm/lib/install/inflate-shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-dev-dep' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-extraneous' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-fs-access-available' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-only-dev' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-only-optional' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-opt-dep' {
  declare module.exports: any;
}

declare module 'npm/lib/install/is-prod-dep' {
  declare module.exports: any;
}

declare module 'npm/lib/install/module-staging-path' {
  declare module.exports: any;
}

declare module 'npm/lib/install/mutate-into-logical-tree' {
  declare module.exports: any;
}

declare module 'npm/lib/install/node' {
  declare module.exports: any;
}

declare module 'npm/lib/install/read-shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/lib/install/realize-shrinkwrap-specifier' {
  declare module.exports: any;
}

declare module 'npm/lib/install/report-optional-failure' {
  declare module.exports: any;
}

declare module 'npm/lib/install/save' {
  declare module.exports: any;
}

declare module 'npm/lib/install/update-package-json' {
  declare module.exports: any;
}

declare module 'npm/lib/install/validate-args' {
  declare module.exports: any;
}

declare module 'npm/lib/install/validate-tree' {
  declare module.exports: any;
}

declare module 'npm/lib/install/writable' {
  declare module.exports: any;
}

declare module 'npm/lib/link' {
  declare module.exports: any;
}

declare module 'npm/lib/logout' {
  declare module.exports: any;
}

declare module 'npm/lib/ls' {
  declare module.exports: any;
}

declare module 'npm/lib/npm' {
  declare module.exports: any;
}

declare module 'npm/lib/outdated' {
  declare module.exports: any;
}

declare module 'npm/lib/owner' {
  declare module.exports: any;
}

declare module 'npm/lib/pack' {
  declare module.exports: any;
}

declare module 'npm/lib/ping' {
  declare module.exports: any;
}

declare module 'npm/lib/prefix' {
  declare module.exports: any;
}

declare module 'npm/lib/profile' {
  declare module.exports: any;
}

declare module 'npm/lib/prune' {
  declare module.exports: any;
}

declare module 'npm/lib/publish' {
  declare module.exports: any;
}

declare module 'npm/lib/rebuild' {
  declare module.exports: any;
}

declare module 'npm/lib/repo' {
  declare module.exports: any;
}

declare module 'npm/lib/restart' {
  declare module.exports: any;
}

declare module 'npm/lib/root' {
  declare module.exports: any;
}

declare module 'npm/lib/run-script' {
  declare module.exports: any;
}

declare module 'npm/lib/search' {
  declare module.exports: any;
}

declare module 'npm/lib/search/all-package-metadata' {
  declare module.exports: any;
}

declare module 'npm/lib/search/all-package-search' {
  declare module.exports: any;
}

declare module 'npm/lib/search/esearch' {
  declare module.exports: any;
}

declare module 'npm/lib/search/format-package-stream' {
  declare module.exports: any;
}

declare module 'npm/lib/search/package-filter' {
  declare module.exports: any;
}

declare module 'npm/lib/set' {
  declare module.exports: any;
}

declare module 'npm/lib/shrinkwrap' {
  declare module.exports: any;
}

declare module 'npm/lib/star' {
  declare module.exports: any;
}

declare module 'npm/lib/stars' {
  declare module.exports: any;
}

declare module 'npm/lib/start' {
  declare module.exports: any;
}

declare module 'npm/lib/stop' {
  declare module.exports: any;
}

declare module 'npm/lib/substack' {
  declare module.exports: any;
}

declare module 'npm/lib/team' {
  declare module.exports: any;
}

declare module 'npm/lib/test' {
  declare module.exports: any;
}

declare module 'npm/lib/token' {
  declare module.exports: any;
}

declare module 'npm/lib/unbuild' {
  declare module.exports: any;
}

declare module 'npm/lib/uninstall' {
  declare module.exports: any;
}

declare module 'npm/lib/unpublish' {
  declare module.exports: any;
}

declare module 'npm/lib/update' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/ansi-trim' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/child-path' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/file-completion' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-deep' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/completion/installed-shallow' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/correct-mkdir' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/deep-sort-object' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/depr-check' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/did-you-mean' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/error-handler' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/error-message' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/escape-arg' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/escape-exec-path' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/gently-rm' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/get-publish-config' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/git' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/gunzip-maybe' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-registry' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows-bash' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows-shell' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/is-windows' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/lifecycle-cmd' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/lifecycle' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/link' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/locker' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/map-to-registry' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/metrics-launch' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/metrics' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/module-name' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/move' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/no-progress-while-running' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/open-url' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/output' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/package-id' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/parse-json' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/perf' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/pick-manifest-from-registry-metadata' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/pulse-till-done' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-local-package' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/read-user-info' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/save-stack' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/spawn' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/temp-filename' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/umask' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/unix-format-path' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/unsupported' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/usage' {
  declare module.exports: any;
}

declare module 'npm/lib/utils/warn-deprecated' {
  declare module.exports: any;
}

declare module 'npm/lib/version' {
  declare module.exports: any;
}

declare module 'npm/lib/view' {
  declare module.exports: any;
}

declare module 'npm/lib/visnup' {
  declare module.exports: any;
}

declare module 'npm/lib/whoami' {
  declare module.exports: any;
}

declare module 'npm/lib/xmas' {
  declare module.exports: any;
}

declare module 'npm/scripts/changelog' {
  declare module.exports: any;
}

declare module 'npm/scripts/gen-dev-ignores' {
  declare module.exports: any;
}

declare module 'npm/scripts/index-build' {
  declare module.exports: any;
}

declare module 'npm/scripts/publish-tag' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm/bin/npm-cli.js' {
  declare module.exports: $Exports<'npm/bin/npm-cli'>;
}
declare module 'npm/bin/npx-cli.js' {
  declare module.exports: $Exports<'npm/bin/npx-cli'>;
}
declare module 'npm/html/static/toc.js' {
  declare module.exports: $Exports<'npm/html/static/toc'>;
}
declare module 'npm/lib/access.js' {
  declare module.exports: $Exports<'npm/lib/access'>;
}
declare module 'npm/lib/adduser.js' {
  declare module.exports: $Exports<'npm/lib/adduser'>;
}
declare module 'npm/lib/audit.js' {
  declare module.exports: $Exports<'npm/lib/audit'>;
}
declare module 'npm/lib/auth/legacy.js' {
  declare module.exports: $Exports<'npm/lib/auth/legacy'>;
}
declare module 'npm/lib/auth/oauth.js' {
  declare module.exports: $Exports<'npm/lib/auth/oauth'>;
}
declare module 'npm/lib/auth/saml.js' {
  declare module.exports: $Exports<'npm/lib/auth/saml'>;
}
declare module 'npm/lib/auth/sso.js' {
  declare module.exports: $Exports<'npm/lib/auth/sso'>;
}
declare module 'npm/lib/bin.js' {
  declare module.exports: $Exports<'npm/lib/bin'>;
}
declare module 'npm/lib/bugs.js' {
  declare module.exports: $Exports<'npm/lib/bugs'>;
}
declare module 'npm/lib/build.js' {
  declare module.exports: $Exports<'npm/lib/build'>;
}
declare module 'npm/lib/cache.js' {
  declare module.exports: $Exports<'npm/lib/cache'>;
}
declare module 'npm/lib/ci.js' {
  declare module.exports: $Exports<'npm/lib/ci'>;
}
declare module 'npm/lib/completion.js' {
  declare module.exports: $Exports<'npm/lib/completion'>;
}
declare module 'npm/lib/config.js' {
  declare module.exports: $Exports<'npm/lib/config'>;
}
declare module 'npm/lib/config/bin-links.js' {
  declare module.exports: $Exports<'npm/lib/config/bin-links'>;
}
declare module 'npm/lib/config/clear-credentials-by-uri.js' {
  declare module.exports: $Exports<'npm/lib/config/clear-credentials-by-uri'>;
}
declare module 'npm/lib/config/cmd-list.js' {
  declare module.exports: $Exports<'npm/lib/config/cmd-list'>;
}
declare module 'npm/lib/config/core.js' {
  declare module.exports: $Exports<'npm/lib/config/core'>;
}
declare module 'npm/lib/config/defaults.js' {
  declare module.exports: $Exports<'npm/lib/config/defaults'>;
}
declare module 'npm/lib/config/fetch-opts.js' {
  declare module.exports: $Exports<'npm/lib/config/fetch-opts'>;
}
declare module 'npm/lib/config/gentle-fs.js' {
  declare module.exports: $Exports<'npm/lib/config/gentle-fs'>;
}
declare module 'npm/lib/config/get-credentials-by-uri.js' {
  declare module.exports: $Exports<'npm/lib/config/get-credentials-by-uri'>;
}
declare module 'npm/lib/config/lifecycle.js' {
  declare module.exports: $Exports<'npm/lib/config/lifecycle'>;
}
declare module 'npm/lib/config/load-cafile.js' {
  declare module.exports: $Exports<'npm/lib/config/load-cafile'>;
}
declare module 'npm/lib/config/load-prefix.js' {
  declare module.exports: $Exports<'npm/lib/config/load-prefix'>;
}
declare module 'npm/lib/config/load-uid.js' {
  declare module.exports: $Exports<'npm/lib/config/load-uid'>;
}
declare module 'npm/lib/config/nerf-dart.js' {
  declare module.exports: $Exports<'npm/lib/config/nerf-dart'>;
}
declare module 'npm/lib/config/pacote.js' {
  declare module.exports: $Exports<'npm/lib/config/pacote'>;
}
declare module 'npm/lib/config/reg-client.js' {
  declare module.exports: $Exports<'npm/lib/config/reg-client'>;
}
declare module 'npm/lib/config/set-credentials-by-uri.js' {
  declare module.exports: $Exports<'npm/lib/config/set-credentials-by-uri'>;
}
declare module 'npm/lib/config/set-user.js' {
  declare module.exports: $Exports<'npm/lib/config/set-user'>;
}
declare module 'npm/lib/dedupe.js' {
  declare module.exports: $Exports<'npm/lib/dedupe'>;
}
declare module 'npm/lib/deprecate.js' {
  declare module.exports: $Exports<'npm/lib/deprecate'>;
}
declare module 'npm/lib/dist-tag.js' {
  declare module.exports: $Exports<'npm/lib/dist-tag'>;
}
declare module 'npm/lib/docs.js' {
  declare module.exports: $Exports<'npm/lib/docs'>;
}
declare module 'npm/lib/doctor.js' {
  declare module.exports: $Exports<'npm/lib/doctor'>;
}
declare module 'npm/lib/doctor/check-files-permission.js' {
  declare module.exports: $Exports<'npm/lib/doctor/check-files-permission'>;
}
declare module 'npm/lib/doctor/check-ping.js' {
  declare module.exports: $Exports<'npm/lib/doctor/check-ping'>;
}
declare module 'npm/lib/doctor/get-git-path.js' {
  declare module.exports: $Exports<'npm/lib/doctor/get-git-path'>;
}
declare module 'npm/lib/doctor/get-latest-nodejs-version.js' {
  declare module.exports: $Exports<'npm/lib/doctor/get-latest-nodejs-version'>;
}
declare module 'npm/lib/doctor/get-latest-npm-version.js' {
  declare module.exports: $Exports<'npm/lib/doctor/get-latest-npm-version'>;
}
declare module 'npm/lib/doctor/verify-cached-files.js' {
  declare module.exports: $Exports<'npm/lib/doctor/verify-cached-files'>;
}
declare module 'npm/lib/edit.js' {
  declare module.exports: $Exports<'npm/lib/edit'>;
}
declare module 'npm/lib/explore.js' {
  declare module.exports: $Exports<'npm/lib/explore'>;
}
declare module 'npm/lib/fetch-package-metadata.js' {
  declare module.exports: $Exports<'npm/lib/fetch-package-metadata'>;
}
declare module 'npm/lib/get.js' {
  declare module.exports: $Exports<'npm/lib/get'>;
}
declare module 'npm/lib/help-search.js' {
  declare module.exports: $Exports<'npm/lib/help-search'>;
}
declare module 'npm/lib/help.js' {
  declare module.exports: $Exports<'npm/lib/help'>;
}
declare module 'npm/lib/hook.js' {
  declare module.exports: $Exports<'npm/lib/hook'>;
}
declare module 'npm/lib/init.js' {
  declare module.exports: $Exports<'npm/lib/init'>;
}
declare module 'npm/lib/install-ci-test.js' {
  declare module.exports: $Exports<'npm/lib/install-ci-test'>;
}
declare module 'npm/lib/install-test.js' {
  declare module.exports: $Exports<'npm/lib/install-test'>;
}
declare module 'npm/lib/install.js' {
  declare module.exports: $Exports<'npm/lib/install'>;
}
declare module 'npm/lib/install/access-error.js' {
  declare module.exports: $Exports<'npm/lib/install/access-error'>;
}
declare module 'npm/lib/install/action/build.js' {
  declare module.exports: $Exports<'npm/lib/install/action/build'>;
}
declare module 'npm/lib/install/action/extract-worker.js' {
  declare module.exports: $Exports<'npm/lib/install/action/extract-worker'>;
}
declare module 'npm/lib/install/action/extract.js' {
  declare module.exports: $Exports<'npm/lib/install/action/extract'>;
}
declare module 'npm/lib/install/action/fetch.js' {
  declare module.exports: $Exports<'npm/lib/install/action/fetch'>;
}
declare module 'npm/lib/install/action/finalize.js' {
  declare module.exports: $Exports<'npm/lib/install/action/finalize'>;
}
declare module 'npm/lib/install/action/global-install.js' {
  declare module.exports: $Exports<'npm/lib/install/action/global-install'>;
}
declare module 'npm/lib/install/action/global-link.js' {
  declare module.exports: $Exports<'npm/lib/install/action/global-link'>;
}
declare module 'npm/lib/install/action/install.js' {
  declare module.exports: $Exports<'npm/lib/install/action/install'>;
}
declare module 'npm/lib/install/action/move.js' {
  declare module.exports: $Exports<'npm/lib/install/action/move'>;
}
declare module 'npm/lib/install/action/postinstall.js' {
  declare module.exports: $Exports<'npm/lib/install/action/postinstall'>;
}
declare module 'npm/lib/install/action/preinstall.js' {
  declare module.exports: $Exports<'npm/lib/install/action/preinstall'>;
}
declare module 'npm/lib/install/action/prepare.js' {
  declare module.exports: $Exports<'npm/lib/install/action/prepare'>;
}
declare module 'npm/lib/install/action/refresh-package-json.js' {
  declare module.exports: $Exports<'npm/lib/install/action/refresh-package-json'>;
}
declare module 'npm/lib/install/action/remove.js' {
  declare module.exports: $Exports<'npm/lib/install/action/remove'>;
}
declare module 'npm/lib/install/action/unbuild.js' {
  declare module.exports: $Exports<'npm/lib/install/action/unbuild'>;
}
declare module 'npm/lib/install/actions.js' {
  declare module.exports: $Exports<'npm/lib/install/actions'>;
}
declare module 'npm/lib/install/and-add-parent-to-errors.js' {
  declare module.exports: $Exports<'npm/lib/install/and-add-parent-to-errors'>;
}
declare module 'npm/lib/install/and-finish-tracker.js' {
  declare module.exports: $Exports<'npm/lib/install/and-finish-tracker'>;
}
declare module 'npm/lib/install/and-ignore-errors.js' {
  declare module.exports: $Exports<'npm/lib/install/and-ignore-errors'>;
}
declare module 'npm/lib/install/audit.js' {
  declare module.exports: $Exports<'npm/lib/install/audit'>;
}
declare module 'npm/lib/install/check-permissions.js' {
  declare module.exports: $Exports<'npm/lib/install/check-permissions'>;
}
declare module 'npm/lib/install/copy-tree.js' {
  declare module.exports: $Exports<'npm/lib/install/copy-tree'>;
}
declare module 'npm/lib/install/decompose-actions.js' {
  declare module.exports: $Exports<'npm/lib/install/decompose-actions'>;
}
declare module 'npm/lib/install/deps.js' {
  declare module.exports: $Exports<'npm/lib/install/deps'>;
}
declare module 'npm/lib/install/diff-trees.js' {
  declare module.exports: $Exports<'npm/lib/install/diff-trees'>;
}
declare module 'npm/lib/install/exists.js' {
  declare module.exports: $Exports<'npm/lib/install/exists'>;
}
declare module 'npm/lib/install/flatten-tree.js' {
  declare module.exports: $Exports<'npm/lib/install/flatten-tree'>;
}
declare module 'npm/lib/install/get-requested.js' {
  declare module.exports: $Exports<'npm/lib/install/get-requested'>;
}
declare module 'npm/lib/install/has-modern-meta.js' {
  declare module.exports: $Exports<'npm/lib/install/has-modern-meta'>;
}
declare module 'npm/lib/install/inflate-bundled.js' {
  declare module.exports: $Exports<'npm/lib/install/inflate-bundled'>;
}
declare module 'npm/lib/install/inflate-shrinkwrap.js' {
  declare module.exports: $Exports<'npm/lib/install/inflate-shrinkwrap'>;
}
declare module 'npm/lib/install/is-dev-dep.js' {
  declare module.exports: $Exports<'npm/lib/install/is-dev-dep'>;
}
declare module 'npm/lib/install/is-extraneous.js' {
  declare module.exports: $Exports<'npm/lib/install/is-extraneous'>;
}
declare module 'npm/lib/install/is-fs-access-available.js' {
  declare module.exports: $Exports<'npm/lib/install/is-fs-access-available'>;
}
declare module 'npm/lib/install/is-only-dev.js' {
  declare module.exports: $Exports<'npm/lib/install/is-only-dev'>;
}
declare module 'npm/lib/install/is-only-optional.js' {
  declare module.exports: $Exports<'npm/lib/install/is-only-optional'>;
}
declare module 'npm/lib/install/is-opt-dep.js' {
  declare module.exports: $Exports<'npm/lib/install/is-opt-dep'>;
}
declare module 'npm/lib/install/is-prod-dep.js' {
  declare module.exports: $Exports<'npm/lib/install/is-prod-dep'>;
}
declare module 'npm/lib/install/module-staging-path.js' {
  declare module.exports: $Exports<'npm/lib/install/module-staging-path'>;
}
declare module 'npm/lib/install/mutate-into-logical-tree.js' {
  declare module.exports: $Exports<'npm/lib/install/mutate-into-logical-tree'>;
}
declare module 'npm/lib/install/node.js' {
  declare module.exports: $Exports<'npm/lib/install/node'>;
}
declare module 'npm/lib/install/read-shrinkwrap.js' {
  declare module.exports: $Exports<'npm/lib/install/read-shrinkwrap'>;
}
declare module 'npm/lib/install/realize-shrinkwrap-specifier.js' {
  declare module.exports: $Exports<'npm/lib/install/realize-shrinkwrap-specifier'>;
}
declare module 'npm/lib/install/report-optional-failure.js' {
  declare module.exports: $Exports<'npm/lib/install/report-optional-failure'>;
}
declare module 'npm/lib/install/save.js' {
  declare module.exports: $Exports<'npm/lib/install/save'>;
}
declare module 'npm/lib/install/update-package-json.js' {
  declare module.exports: $Exports<'npm/lib/install/update-package-json'>;
}
declare module 'npm/lib/install/validate-args.js' {
  declare module.exports: $Exports<'npm/lib/install/validate-args'>;
}
declare module 'npm/lib/install/validate-tree.js' {
  declare module.exports: $Exports<'npm/lib/install/validate-tree'>;
}
declare module 'npm/lib/install/writable.js' {
  declare module.exports: $Exports<'npm/lib/install/writable'>;
}
declare module 'npm/lib/link.js' {
  declare module.exports: $Exports<'npm/lib/link'>;
}
declare module 'npm/lib/logout.js' {
  declare module.exports: $Exports<'npm/lib/logout'>;
}
declare module 'npm/lib/ls.js' {
  declare module.exports: $Exports<'npm/lib/ls'>;
}
declare module 'npm/lib/npm.js' {
  declare module.exports: $Exports<'npm/lib/npm'>;
}
declare module 'npm/lib/outdated.js' {
  declare module.exports: $Exports<'npm/lib/outdated'>;
}
declare module 'npm/lib/owner.js' {
  declare module.exports: $Exports<'npm/lib/owner'>;
}
declare module 'npm/lib/pack.js' {
  declare module.exports: $Exports<'npm/lib/pack'>;
}
declare module 'npm/lib/ping.js' {
  declare module.exports: $Exports<'npm/lib/ping'>;
}
declare module 'npm/lib/prefix.js' {
  declare module.exports: $Exports<'npm/lib/prefix'>;
}
declare module 'npm/lib/profile.js' {
  declare module.exports: $Exports<'npm/lib/profile'>;
}
declare module 'npm/lib/prune.js' {
  declare module.exports: $Exports<'npm/lib/prune'>;
}
declare module 'npm/lib/publish.js' {
  declare module.exports: $Exports<'npm/lib/publish'>;
}
declare module 'npm/lib/rebuild.js' {
  declare module.exports: $Exports<'npm/lib/rebuild'>;
}
declare module 'npm/lib/repo.js' {
  declare module.exports: $Exports<'npm/lib/repo'>;
}
declare module 'npm/lib/restart.js' {
  declare module.exports: $Exports<'npm/lib/restart'>;
}
declare module 'npm/lib/root.js' {
  declare module.exports: $Exports<'npm/lib/root'>;
}
declare module 'npm/lib/run-script.js' {
  declare module.exports: $Exports<'npm/lib/run-script'>;
}
declare module 'npm/lib/search.js' {
  declare module.exports: $Exports<'npm/lib/search'>;
}
declare module 'npm/lib/search/all-package-metadata.js' {
  declare module.exports: $Exports<'npm/lib/search/all-package-metadata'>;
}
declare module 'npm/lib/search/all-package-search.js' {
  declare module.exports: $Exports<'npm/lib/search/all-package-search'>;
}
declare module 'npm/lib/search/esearch.js' {
  declare module.exports: $Exports<'npm/lib/search/esearch'>;
}
declare module 'npm/lib/search/format-package-stream.js' {
  declare module.exports: $Exports<'npm/lib/search/format-package-stream'>;
}
declare module 'npm/lib/search/package-filter.js' {
  declare module.exports: $Exports<'npm/lib/search/package-filter'>;
}
declare module 'npm/lib/set.js' {
  declare module.exports: $Exports<'npm/lib/set'>;
}
declare module 'npm/lib/shrinkwrap.js' {
  declare module.exports: $Exports<'npm/lib/shrinkwrap'>;
}
declare module 'npm/lib/star.js' {
  declare module.exports: $Exports<'npm/lib/star'>;
}
declare module 'npm/lib/stars.js' {
  declare module.exports: $Exports<'npm/lib/stars'>;
}
declare module 'npm/lib/start.js' {
  declare module.exports: $Exports<'npm/lib/start'>;
}
declare module 'npm/lib/stop.js' {
  declare module.exports: $Exports<'npm/lib/stop'>;
}
declare module 'npm/lib/substack.js' {
  declare module.exports: $Exports<'npm/lib/substack'>;
}
declare module 'npm/lib/team.js' {
  declare module.exports: $Exports<'npm/lib/team'>;
}
declare module 'npm/lib/test.js' {
  declare module.exports: $Exports<'npm/lib/test'>;
}
declare module 'npm/lib/token.js' {
  declare module.exports: $Exports<'npm/lib/token'>;
}
declare module 'npm/lib/unbuild.js' {
  declare module.exports: $Exports<'npm/lib/unbuild'>;
}
declare module 'npm/lib/uninstall.js' {
  declare module.exports: $Exports<'npm/lib/uninstall'>;
}
declare module 'npm/lib/unpublish.js' {
  declare module.exports: $Exports<'npm/lib/unpublish'>;
}
declare module 'npm/lib/update.js' {
  declare module.exports: $Exports<'npm/lib/update'>;
}
declare module 'npm/lib/utils/ansi-trim.js' {
  declare module.exports: $Exports<'npm/lib/utils/ansi-trim'>;
}
declare module 'npm/lib/utils/child-path.js' {
  declare module.exports: $Exports<'npm/lib/utils/child-path'>;
}
declare module 'npm/lib/utils/completion/file-completion.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/file-completion'>;
}
declare module 'npm/lib/utils/completion/installed-deep.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-deep'>;
}
declare module 'npm/lib/utils/completion/installed-shallow.js' {
  declare module.exports: $Exports<'npm/lib/utils/completion/installed-shallow'>;
}
declare module 'npm/lib/utils/correct-mkdir.js' {
  declare module.exports: $Exports<'npm/lib/utils/correct-mkdir'>;
}
declare module 'npm/lib/utils/deep-sort-object.js' {
  declare module.exports: $Exports<'npm/lib/utils/deep-sort-object'>;
}
declare module 'npm/lib/utils/depr-check.js' {
  declare module.exports: $Exports<'npm/lib/utils/depr-check'>;
}
declare module 'npm/lib/utils/did-you-mean.js' {
  declare module.exports: $Exports<'npm/lib/utils/did-you-mean'>;
}
declare module 'npm/lib/utils/error-handler.js' {
  declare module.exports: $Exports<'npm/lib/utils/error-handler'>;
}
declare module 'npm/lib/utils/error-message.js' {
  declare module.exports: $Exports<'npm/lib/utils/error-message'>;
}
declare module 'npm/lib/utils/escape-arg.js' {
  declare module.exports: $Exports<'npm/lib/utils/escape-arg'>;
}
declare module 'npm/lib/utils/escape-exec-path.js' {
  declare module.exports: $Exports<'npm/lib/utils/escape-exec-path'>;
}
declare module 'npm/lib/utils/gently-rm.js' {
  declare module.exports: $Exports<'npm/lib/utils/gently-rm'>;
}
declare module 'npm/lib/utils/get-publish-config.js' {
  declare module.exports: $Exports<'npm/lib/utils/get-publish-config'>;
}
declare module 'npm/lib/utils/git.js' {
  declare module.exports: $Exports<'npm/lib/utils/git'>;
}
declare module 'npm/lib/utils/gunzip-maybe.js' {
  declare module.exports: $Exports<'npm/lib/utils/gunzip-maybe'>;
}
declare module 'npm/lib/utils/is-registry.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-registry'>;
}
declare module 'npm/lib/utils/is-windows-bash.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows-bash'>;
}
declare module 'npm/lib/utils/is-windows-shell.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows-shell'>;
}
declare module 'npm/lib/utils/is-windows.js' {
  declare module.exports: $Exports<'npm/lib/utils/is-windows'>;
}
declare module 'npm/lib/utils/lifecycle-cmd.js' {
  declare module.exports: $Exports<'npm/lib/utils/lifecycle-cmd'>;
}
declare module 'npm/lib/utils/lifecycle.js' {
  declare module.exports: $Exports<'npm/lib/utils/lifecycle'>;
}
declare module 'npm/lib/utils/link.js' {
  declare module.exports: $Exports<'npm/lib/utils/link'>;
}
declare module 'npm/lib/utils/locker.js' {
  declare module.exports: $Exports<'npm/lib/utils/locker'>;
}
declare module 'npm/lib/utils/map-to-registry.js' {
  declare module.exports: $Exports<'npm/lib/utils/map-to-registry'>;
}
declare module 'npm/lib/utils/metrics-launch.js' {
  declare module.exports: $Exports<'npm/lib/utils/metrics-launch'>;
}
declare module 'npm/lib/utils/metrics.js' {
  declare module.exports: $Exports<'npm/lib/utils/metrics'>;
}
declare module 'npm/lib/utils/module-name.js' {
  declare module.exports: $Exports<'npm/lib/utils/module-name'>;
}
declare module 'npm/lib/utils/move.js' {
  declare module.exports: $Exports<'npm/lib/utils/move'>;
}
declare module 'npm/lib/utils/no-progress-while-running.js' {
  declare module.exports: $Exports<'npm/lib/utils/no-progress-while-running'>;
}
declare module 'npm/lib/utils/open-url.js' {
  declare module.exports: $Exports<'npm/lib/utils/open-url'>;
}
declare module 'npm/lib/utils/output.js' {
  declare module.exports: $Exports<'npm/lib/utils/output'>;
}
declare module 'npm/lib/utils/package-id.js' {
  declare module.exports: $Exports<'npm/lib/utils/package-id'>;
}
declare module 'npm/lib/utils/parse-json.js' {
  declare module.exports: $Exports<'npm/lib/utils/parse-json'>;
}
declare module 'npm/lib/utils/perf.js' {
  declare module.exports: $Exports<'npm/lib/utils/perf'>;
}
declare module 'npm/lib/utils/pick-manifest-from-registry-metadata.js' {
  declare module.exports: $Exports<'npm/lib/utils/pick-manifest-from-registry-metadata'>;
}
declare module 'npm/lib/utils/pulse-till-done.js' {
  declare module.exports: $Exports<'npm/lib/utils/pulse-till-done'>;
}
declare module 'npm/lib/utils/read-local-package.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-local-package'>;
}
declare module 'npm/lib/utils/read-user-info.js' {
  declare module.exports: $Exports<'npm/lib/utils/read-user-info'>;
}
declare module 'npm/lib/utils/save-stack.js' {
  declare module.exports: $Exports<'npm/lib/utils/save-stack'>;
}
declare module 'npm/lib/utils/spawn.js' {
  declare module.exports: $Exports<'npm/lib/utils/spawn'>;
}
declare module 'npm/lib/utils/temp-filename.js' {
  declare module.exports: $Exports<'npm/lib/utils/temp-filename'>;
}
declare module 'npm/lib/utils/umask.js' {
  declare module.exports: $Exports<'npm/lib/utils/umask'>;
}
declare module 'npm/lib/utils/unix-format-path.js' {
  declare module.exports: $Exports<'npm/lib/utils/unix-format-path'>;
}
declare module 'npm/lib/utils/unsupported.js' {
  declare module.exports: $Exports<'npm/lib/utils/unsupported'>;
}
declare module 'npm/lib/utils/usage.js' {
  declare module.exports: $Exports<'npm/lib/utils/usage'>;
}
declare module 'npm/lib/utils/warn-deprecated.js' {
  declare module.exports: $Exports<'npm/lib/utils/warn-deprecated'>;
}
declare module 'npm/lib/version.js' {
  declare module.exports: $Exports<'npm/lib/version'>;
}
declare module 'npm/lib/view.js' {
  declare module.exports: $Exports<'npm/lib/view'>;
}
declare module 'npm/lib/visnup.js' {
  declare module.exports: $Exports<'npm/lib/visnup'>;
}
declare module 'npm/lib/whoami.js' {
  declare module.exports: $Exports<'npm/lib/whoami'>;
}
declare module 'npm/lib/xmas.js' {
  declare module.exports: $Exports<'npm/lib/xmas'>;
}
declare module 'npm/scripts/changelog.js' {
  declare module.exports: $Exports<'npm/scripts/changelog'>;
}
declare module 'npm/scripts/gen-dev-ignores.js' {
  declare module.exports: $Exports<'npm/scripts/gen-dev-ignores'>;
}
declare module 'npm/scripts/index-build.js' {
  declare module.exports: $Exports<'npm/scripts/index-build'>;
}
declare module 'npm/scripts/publish-tag.js' {
  declare module.exports: $Exports<'npm/scripts/publish-tag'>;
}
