// flow-typed signature: 01728d34f14731369f803a063558f307
// flow-typed version: <<STUB>>/vinyl-buffer_v^1.0.1/flow_v0.85.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vinyl-buffer'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vinyl-buffer' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vinyl-buffer/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vinyl-buffer/index' {
  declare module.exports: $Exports<'vinyl-buffer'>;
}
declare module 'vinyl-buffer/index.js' {
  declare module.exports: $Exports<'vinyl-buffer'>;
}
declare module 'vinyl-buffer/test.js' {
  declare module.exports: $Exports<'vinyl-buffer/test'>;
}
