
export const OPEN_HEADER_MENU_ID = "OPEN_HEADER_MENU_ID";
export const CLOSE_HEADER_MENU_ID = "CLOSE_HEADER_MENU_ID";

export const OPEN_HEADER_POPUP_ID = "OPEN_HEADER_POPUP_ID";
export const CLOSE_HEADER_POPUP_ID = "CLOSE_HEADER_POPUP_ID";
