// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.7.0
//   protoc               v6.30.2
// source: src/projects/digital/site/src/proto/DigitalCircuit.proto

/* eslint-disable */
import { BinaryReader, BinaryWriter } from "@bufbuild/protobuf/wire";
import { Circuit } from "../../../../shared/site/src/proto/Circuit";

export const protobufPackage = "";

/** TODO[model_refactor_api] - .gitignore the generated .ts and generate it automatically via webpack? */

export interface DigitalSimState {
  /** Array of signals corresponding to the flat(circuit.components.map(allPorts)) */
  signals: DigitalSimState_Signal[];
  /** index of component in circuit.components : state of the component */
  states: { [key: number]: DigitalSimState_State };
  /** index of component in circuit.components : state of the component */
  icStates: { [key: number]: DigitalSimState };
}

export enum DigitalSimState_Signal {
  Off = 0,
  On = 1,
  Metastable = 2,
  UNRECOGNIZED = -1,
}

export function digitalSimState_SignalFromJSON(object: any): DigitalSimState_Signal {
  switch (object) {
    case 0:
    case "Off":
      return DigitalSimState_Signal.Off;
    case 1:
    case "On":
      return DigitalSimState_Signal.On;
    case 2:
    case "Metastable":
      return DigitalSimState_Signal.Metastable;
    case -1:
    case "UNRECOGNIZED":
    default:
      return DigitalSimState_Signal.UNRECOGNIZED;
  }
}

export function digitalSimState_SignalToJSON(object: DigitalSimState_Signal): string {
  switch (object) {
    case DigitalSimState_Signal.Off:
      return "Off";
    case DigitalSimState_Signal.On:
      return "On";
    case DigitalSimState_Signal.Metastable:
      return "Metastable";
    case DigitalSimState_Signal.UNRECOGNIZED:
    default:
      return "UNRECOGNIZED";
  }
}

export interface DigitalSimState_State {
  state: DigitalSimState_Signal[];
}

export interface DigitalSimState_StatesEntry {
  key: number;
  value: DigitalSimState_State | undefined;
}

export interface DigitalSimState_IcStatesEntry {
  key: number;
  value: DigitalSimState | undefined;
}

export interface DigitalCircuit {
  circuit: Circuit | undefined;
  propagationTime: number;
  /** Array of IC states corresponding to circuit.ics */
  icInitialSimStates: DigitalSimState[];
  simState: DigitalSimState | undefined;
}

function createBaseDigitalSimState(): DigitalSimState {
  return { signals: [], states: {}, icStates: {} };
}

export const DigitalSimState: MessageFns<DigitalSimState> = {
  encode(message: DigitalSimState, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.signals) {
      writer.int32(v);
    }
    writer.join();
    Object.entries(message.states).forEach(([key, value]) => {
      DigitalSimState_StatesEntry.encode({ key: key as any, value }, writer.uint32(18).fork()).join();
    });
    Object.entries(message.icStates).forEach(([key, value]) => {
      DigitalSimState_IcStatesEntry.encode({ key: key as any, value }, writer.uint32(26).fork()).join();
    });
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DigitalSimState {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDigitalSimState();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.signals.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.signals.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          const entry2 = DigitalSimState_StatesEntry.decode(reader, reader.uint32());
          if (entry2.value !== undefined) {
            message.states[entry2.key] = entry2.value;
          }
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          const entry3 = DigitalSimState_IcStatesEntry.decode(reader, reader.uint32());
          if (entry3.value !== undefined) {
            message.icStates[entry3.key] = entry3.value;
          }
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DigitalSimState {
    return {
      signals: globalThis.Array.isArray(object?.signals)
        ? object.signals.map((e: any) => digitalSimState_SignalFromJSON(e))
        : [],
      states: isObject(object.states)
        ? Object.entries(object.states).reduce<{ [key: number]: DigitalSimState_State }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = DigitalSimState_State.fromJSON(value);
          return acc;
        }, {})
        : {},
      icStates: isObject(object.icStates)
        ? Object.entries(object.icStates).reduce<{ [key: number]: DigitalSimState }>((acc, [key, value]) => {
          acc[globalThis.Number(key)] = DigitalSimState.fromJSON(value);
          return acc;
        }, {})
        : {},
    };
  },

  toJSON(message: DigitalSimState): unknown {
    const obj: any = {};
    if (message.signals?.length) {
      obj.signals = message.signals.map((e) => digitalSimState_SignalToJSON(e));
    }
    if (message.states) {
      const entries = Object.entries(message.states);
      if (entries.length > 0) {
        obj.states = {};
        entries.forEach(([k, v]) => {
          obj.states[k] = DigitalSimState_State.toJSON(v);
        });
      }
    }
    if (message.icStates) {
      const entries = Object.entries(message.icStates);
      if (entries.length > 0) {
        obj.icStates = {};
        entries.forEach(([k, v]) => {
          obj.icStates[k] = DigitalSimState.toJSON(v);
        });
      }
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DigitalSimState>, I>>(base?: I): DigitalSimState {
    return DigitalSimState.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DigitalSimState>, I>>(object: I): DigitalSimState {
    const message = createBaseDigitalSimState();
    message.signals = object.signals?.map((e) => e) || [];
    message.states = Object.entries(object.states ?? {}).reduce<{ [key: number]: DigitalSimState_State }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = DigitalSimState_State.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    message.icStates = Object.entries(object.icStates ?? {}).reduce<{ [key: number]: DigitalSimState }>(
      (acc, [key, value]) => {
        if (value !== undefined) {
          acc[globalThis.Number(key)] = DigitalSimState.fromPartial(value);
        }
        return acc;
      },
      {},
    );
    return message;
  },
};

function createBaseDigitalSimState_State(): DigitalSimState_State {
  return { state: [] };
}

export const DigitalSimState_State: MessageFns<DigitalSimState_State> = {
  encode(message: DigitalSimState_State, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    writer.uint32(10).fork();
    for (const v of message.state) {
      writer.int32(v);
    }
    writer.join();
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DigitalSimState_State {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDigitalSimState_State();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag === 8) {
            message.state.push(reader.int32() as any);

            continue;
          }

          if (tag === 10) {
            const end2 = reader.uint32() + reader.pos;
            while (reader.pos < end2) {
              message.state.push(reader.int32() as any);
            }

            continue;
          }

          break;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DigitalSimState_State {
    return {
      state: globalThis.Array.isArray(object?.state)
        ? object.state.map((e: any) => digitalSimState_SignalFromJSON(e))
        : [],
    };
  },

  toJSON(message: DigitalSimState_State): unknown {
    const obj: any = {};
    if (message.state?.length) {
      obj.state = message.state.map((e) => digitalSimState_SignalToJSON(e));
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DigitalSimState_State>, I>>(base?: I): DigitalSimState_State {
    return DigitalSimState_State.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DigitalSimState_State>, I>>(object: I): DigitalSimState_State {
    const message = createBaseDigitalSimState_State();
    message.state = object.state?.map((e) => e) || [];
    return message;
  },
};

function createBaseDigitalSimState_StatesEntry(): DigitalSimState_StatesEntry {
  return { key: 0, value: undefined };
}

export const DigitalSimState_StatesEntry: MessageFns<DigitalSimState_StatesEntry> = {
  encode(message: DigitalSimState_StatesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).uint32(message.key);
    }
    if (message.value !== undefined) {
      DigitalSimState_State.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DigitalSimState_StatesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDigitalSimState_StatesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = DigitalSimState_State.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DigitalSimState_StatesEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? DigitalSimState_State.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DigitalSimState_StatesEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = DigitalSimState_State.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DigitalSimState_StatesEntry>, I>>(base?: I): DigitalSimState_StatesEntry {
    return DigitalSimState_StatesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DigitalSimState_StatesEntry>, I>>(object: I): DigitalSimState_StatesEntry {
    const message = createBaseDigitalSimState_StatesEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? DigitalSimState_State.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseDigitalSimState_IcStatesEntry(): DigitalSimState_IcStatesEntry {
  return { key: 0, value: undefined };
}

export const DigitalSimState_IcStatesEntry: MessageFns<DigitalSimState_IcStatesEntry> = {
  encode(message: DigitalSimState_IcStatesEntry, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.key !== 0) {
      writer.uint32(8).uint32(message.key);
    }
    if (message.value !== undefined) {
      DigitalSimState.encode(message.value, writer.uint32(18).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DigitalSimState_IcStatesEntry {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDigitalSimState_IcStatesEntry();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 8) {
            break;
          }

          message.key = reader.uint32();
          continue;
        }
        case 2: {
          if (tag !== 18) {
            break;
          }

          message.value = DigitalSimState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DigitalSimState_IcStatesEntry {
    return {
      key: isSet(object.key) ? globalThis.Number(object.key) : 0,
      value: isSet(object.value) ? DigitalSimState.fromJSON(object.value) : undefined,
    };
  },

  toJSON(message: DigitalSimState_IcStatesEntry): unknown {
    const obj: any = {};
    if (message.key !== 0) {
      obj.key = Math.round(message.key);
    }
    if (message.value !== undefined) {
      obj.value = DigitalSimState.toJSON(message.value);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DigitalSimState_IcStatesEntry>, I>>(base?: I): DigitalSimState_IcStatesEntry {
    return DigitalSimState_IcStatesEntry.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DigitalSimState_IcStatesEntry>, I>>(
    object: I,
  ): DigitalSimState_IcStatesEntry {
    const message = createBaseDigitalSimState_IcStatesEntry();
    message.key = object.key ?? 0;
    message.value = (object.value !== undefined && object.value !== null)
      ? DigitalSimState.fromPartial(object.value)
      : undefined;
    return message;
  },
};

function createBaseDigitalCircuit(): DigitalCircuit {
  return { circuit: undefined, propagationTime: 0, icInitialSimStates: [], simState: undefined };
}

export const DigitalCircuit: MessageFns<DigitalCircuit> = {
  encode(message: DigitalCircuit, writer: BinaryWriter = new BinaryWriter()): BinaryWriter {
    if (message.circuit !== undefined) {
      Circuit.encode(message.circuit, writer.uint32(10).fork()).join();
    }
    if (message.propagationTime !== 0) {
      writer.uint32(21).float(message.propagationTime);
    }
    for (const v of message.icInitialSimStates) {
      DigitalSimState.encode(v!, writer.uint32(26).fork()).join();
    }
    if (message.simState !== undefined) {
      DigitalSimState.encode(message.simState, writer.uint32(34).fork()).join();
    }
    return writer;
  },

  decode(input: BinaryReader | Uint8Array, length?: number): DigitalCircuit {
    const reader = input instanceof BinaryReader ? input : new BinaryReader(input);
    let end = length === undefined ? reader.len : reader.pos + length;
    const message = createBaseDigitalCircuit();
    while (reader.pos < end) {
      const tag = reader.uint32();
      switch (tag >>> 3) {
        case 1: {
          if (tag !== 10) {
            break;
          }

          message.circuit = Circuit.decode(reader, reader.uint32());
          continue;
        }
        case 2: {
          if (tag !== 21) {
            break;
          }

          message.propagationTime = reader.float();
          continue;
        }
        case 3: {
          if (tag !== 26) {
            break;
          }

          message.icInitialSimStates.push(DigitalSimState.decode(reader, reader.uint32()));
          continue;
        }
        case 4: {
          if (tag !== 34) {
            break;
          }

          message.simState = DigitalSimState.decode(reader, reader.uint32());
          continue;
        }
      }
      if ((tag & 7) === 4 || tag === 0) {
        break;
      }
      reader.skip(tag & 7);
    }
    return message;
  },

  fromJSON(object: any): DigitalCircuit {
    return {
      circuit: isSet(object.circuit) ? Circuit.fromJSON(object.circuit) : undefined,
      propagationTime: isSet(object.propagationTime) ? globalThis.Number(object.propagationTime) : 0,
      icInitialSimStates: globalThis.Array.isArray(object?.icInitialSimStates)
        ? object.icInitialSimStates.map((e: any) => DigitalSimState.fromJSON(e))
        : [],
      simState: isSet(object.simState) ? DigitalSimState.fromJSON(object.simState) : undefined,
    };
  },

  toJSON(message: DigitalCircuit): unknown {
    const obj: any = {};
    if (message.circuit !== undefined) {
      obj.circuit = Circuit.toJSON(message.circuit);
    }
    if (message.propagationTime !== 0) {
      obj.propagationTime = message.propagationTime;
    }
    if (message.icInitialSimStates?.length) {
      obj.icInitialSimStates = message.icInitialSimStates.map((e) => DigitalSimState.toJSON(e));
    }
    if (message.simState !== undefined) {
      obj.simState = DigitalSimState.toJSON(message.simState);
    }
    return obj;
  },

  create<I extends Exact<DeepPartial<DigitalCircuit>, I>>(base?: I): DigitalCircuit {
    return DigitalCircuit.fromPartial(base ?? ({} as any));
  },
  fromPartial<I extends Exact<DeepPartial<DigitalCircuit>, I>>(object: I): DigitalCircuit {
    const message = createBaseDigitalCircuit();
    message.circuit = (object.circuit !== undefined && object.circuit !== null)
      ? Circuit.fromPartial(object.circuit)
      : undefined;
    message.propagationTime = object.propagationTime ?? 0;
    message.icInitialSimStates = object.icInitialSimStates?.map((e) => DigitalSimState.fromPartial(e)) || [];
    message.simState = (object.simState !== undefined && object.simState !== null)
      ? DigitalSimState.fromPartial(object.simState)
      : undefined;
    return message;
  },
};

type Builtin = Date | Function | Uint8Array | string | number | boolean | undefined;

export type DeepPartial<T> = T extends Builtin ? T
  : T extends globalThis.Array<infer U> ? globalThis.Array<DeepPartial<U>>
  : T extends ReadonlyArray<infer U> ? ReadonlyArray<DeepPartial<U>>
  : T extends {} ? { [K in keyof T]?: DeepPartial<T[K]> }
  : Partial<T>;

type KeysOfUnion<T> = T extends T ? keyof T : never;
export type Exact<P, I extends P> = P extends Builtin ? P
  : P & { [K in keyof P]: Exact<P[K], I[K]> } & { [K in Exclude<keyof I, KeysOfUnion<P>>]: never };

function isObject(value: any): boolean {
  return typeof value === "object" && value !== null;
}

function isSet(value: any): boolean {
  return value !== null && value !== undefined;
}

export interface MessageFns<T> {
  encode(message: T, writer?: BinaryWriter): BinaryWriter;
  decode(input: BinaryReader | Uint8Array, length?: number): T;
  fromJSON(object: any): T;
  toJSON(message: T): unknown;
  create<I extends Exact<DeepPartial<T>, I>>(base?: I): T;
  fromPartial<I extends Exact<DeepPartial<T>, I>>(object: I): T;
}
